### ISSUE TITLE
Can't find aircrack Dictionary file?

### ISSUE THREAD

**Issue by beerkala** [v1s1t0r1sh3r3/airgeddon#101]
1.  (aircrack) Dictionary attack against capture file 

You already have selected a capture file during this session [/root/Desktop/handshake-01.cap] 

Do you want to use this already selected capture file? [Y/n] 
y

You already have selected a BSSID during this session and is present in capture file [E8:FC:AF:F4:4E:6A] 

Do you want to use this already selected BSSID? [Y/n] 
y

You already have selected a dictionary file during this session [/root/Desktop/1] 

Do you want to use this already selected dictionary file? [Y/n] 
n

Enter the path of a dictionary file : 
/root/Desktop/1.txt
The path to the dictionary file is valid. Script can continue... 

the 1.txt file 
root@kali:~# head -n 10 /root/Desktop/1.txt
11111111
2222222

how to fix the error!

**Comment by v1s1t0r1sh3r3** [comment]
Closing this for two reasons.

First reason is you didn't filled the questions of the issue template (versions, etc).

Second reason is your are asking how to fix an error but there is no error shown. You copied and pasted the normal process on which a dictionary file is requested, you set a path of an existing dictionary and the script is saying it is ok. So, no error shown, it makes no sense. Then you show the content of the file which is existing and it has passwords so it's ok too. ¿?

Stop openning non-existing issues or try to improve your english before doing it because based on this and the other issue you opened it seems you are not understanding the messages on the screen.
