### ISSUE TITLE
mac wlan0 to prism0 monitor mode

### ISSUE THREAD

**Issue by best-tech** [v1s1t0r1sh3r3/airgeddon#112]
#### What is your airgeddon version?

last 7.23

#### What is your Linux O.S. and which version?

Kali Linux 2018.1, mac air 2012

#### Which is the chipset of your wireless card?

BCM4322

#### Describe the issue and the steps to reproduce it
after install last version of kali next problem:
(broadcom-sta)[https://unix.stackexchange.com/questions/420879/how-to-install-the-proprietary-driver-wl-after-removing-the-broadcom-sta-packa]
installig broadcom-sta-dkms_6.30.223.271-7_all.deb
turn monitor mode and ill see:
`iwconfig`
```
wlan0     IEEE 802.11  
          Mode:Managed  
          Bit Rate=162 Mb/s   Tx-Power=200 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=40/70  Signal level=-70 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
prism0    no wireless extensions.
``
prism0 working with airodump-ng prism0 but airgeddon talk about find target: prism0 not monitor mode because iwconfig say `prism0    no wireless extensions.` but work correctly

**Comment by v1s1t0r1sh3r3** [comment]
Oh sorry, but it seems it is not an airgeddon problem. Is driver related.

airgeddon works only with airmon compatible cards. So you should find a driver able to change to monitor-managed using airmon. In order to work correctly you should launch:

`airmon-ng start wlan0` <- check if your system has airmon-zc, if you have both (airmon-ng and airmon-zc), you should use airmon-zc instead of airmon-ng. This is something airgeddon already select automatically.

And it is suppossed that after that command if everything goes fine, you should see the card as monitor on `iwconfig`. If this is not working for you sorry, but we can't do anything 🙄 . Let us know your situation with that.

**Comment by xtonousou** [comment]
@best-tech do you have Kali installed in a VM or not? `BCM4322` driver is known to have problems with `airmon-ng`. Anyway, I suggest you buying an external WiFi card that supports monitor mode.

**Comment by best-tech** [comment]
@v1s1t0r1sh3r3 it worked on previous kali version. I thought maybe there are different modes of operation. I will look for the driver, thanks
@xtonousou Iam use install kali, before the update everything worked well. I expect an external card by mail while I'm using the built-in card. Now you have to use each application manually.
