### ISSUE TITLE
Customise the eviltwin fishing layout

### ISSUE THREAD

**Issue by kaspost** [v1s1t0r1sh3r3/airgeddon#132]
Airgeddon version: 8.01
Parrot OS

Hello,
Im using the evil twin attack method in airgeddon. But I have one problem, I live in Sweden and there are no Swedish translations avaible for the fishing page. Thats why im wondering if its possible to add a customised fishing page layout. How do you do that? Would it also then be possible to implent a fishing page specialized for the specific router. For example it may say like "TP LINK 3104" or something on the page.
I hope that I didnt violate any rule when I didnt write in the format presentated. When I posted the issue you couldnt see anything, so I just deleted everything.

**Comment by v1s1t0r1sh3r3** [comment]
Hello, the more ellaborated capture portal is something that has been already discussed here several times. We (the team) think that is better to have a "neutral" page instead of having a portal with router logos or more info. Bear in mind that the "victim's" profile is a profile that doesn't care about that. They usually don't even know anything about the brand of a router... so TP-LINK, CISCO or any other branch sounds strange for him/her. That's the reason the portal page is a lax page.

Anyway, you are free to modify it. I'll tell you some advices about how to do it and where is that at the code:

1. All the displayed messages for evil twin captive portal are on `language_strings.sh` file on the `et_misc_texts` array. So you can change the texts of any language in order to have it on your own language.
2. The html, css, html and js used are created at `airgeddon.sh` file on this function: `set_captive_portal_page`. So feel free to modify it on your own. You can do the changes on code or maybe you may prefer to have the files done (outside airgeddon) and once portal launched overwriting the created files on `/tmp/www` directory with your customized ones.

In any case, if you want to collaborate with the project translating it into sweedish, you are welcome. Read the contributing guidelines [here](https://github.com/v1s1t0r1sh3r3/airgeddon/blob/master/CONTRIBUTING.md).

Closing.

**Comment by WaGi-Coding** [comment]
Hey i wanted to change it in the /tmp/www but i was not finding any folder called www in tmp also when checking on each step. What i did wrong? ^^

Anyway meanwhile i change it in the airgeddon.sh, just wonder i can't locate this folder
