### ISSUE TITLE
[enhancement] option to use tmux instead of xterm for use without x-server

### ISSUE THREAD

**Issue by monte-monte** [v1s1t0r1sh3r3/airgeddon#138]
For now you can use airgeddon only if xwindow system is detected, as it requires multiple xterm windows to be opened for external tools. I don't know if it was a deliberate choice, but using a tmux could be useful if someone wants to use this script via ssh or just prefers command line's clean look. Yesterday I tried to change parts of the code that calls xterm to create separate tmux pane, wait until it closed and then resume the script. 
`tmux split-window -h "airodump-ng -w '${tmpdir}nws' --encrypt '${cypher_filter}' '${interface}' --band ${airodump_band_modifier}';tmux wait-for -S p-airodump-target"`
`tmux wait-for p-airodump-target`
The only drawback of this is that you need to launch entire script in tmux, thus you can't check if tmux is installed in system as it's done with xterm and other required tools.
Should I just fork it and create version for tmux, or it won't be welcomed?

**Comment by OscarAkaElvis** [comment]
This is a major change. To do this for sure tmux must be a requirement and it could replace the xterm on essential tools initial checks (this is easy to do). Then you can change every xterm call using your tmux alternative.... the hard part will come later. A lot of attacks are not as simple as one window opening. A lot of them (wep attack, any evil twin attack, etc) has some windows that must be check by the user during the attack.

For example... on an evil twin attack with sniffing. You should check the control window to see if a user is connected and at the same time you should check the sniffer window to see possible sniffer passwords. How do you plan handle this?

We are open to changes but this is a big change and must have a solid reason to be developed. In my opinion airgeddon tmux based has less functionality than airgeddon xterm based. The unique advantage of tmux is that this can be launched without X window system on a ssh session for example... but if to achieve that, the price to pay is to have less functionality I must say "no thank you".

Maybe instead of a "replacement" (xterm by tmux), could be an option... and it could be nice to have the option to change how it works from an option on the "language and options" menu. Maybe some kind of attacks (most of them) can't be launched on this mode... I don't know.

**Comment by OscarAkaElvis** [comment]
Hi, to be honest I didn't know exactly how tmux works. I saw that the screen can be splitted using tmux... that feature could be valid for us. Maybe the best option could be:

If xterm and a X window system are correctly detected can be used and if not, a second check can be done to use tmux instead. In addition, could be a var in the code linked with a menu option to force tmux mode. That could be a very nice feature... but it is too a very big change. Do you think you are able to perform it? Me (v1s1t0r... yeah, OscarAkaElvis and v1s1t0r are the same person... me) can help! and yes, this should need a different branch to work with. What do you say?

**Comment by monte-monte** [comment]
Okay I see your point. I need to see deeper into airgeddon code, but as far as I know tmux functionality, the issues you addressed aren't really an issue. Tmux has two components - panes and windows. Panes is areas of a main window divided in some layout and you can switch between them easily with shortcut keys or even a mouse. Windows are just windows inside a session and can be switched between too, and could contain division into panes.
The other big advantage of tmux is that it server bases, thus you can detach from session your instance of airgeddon is working in and attach to it later, this is essential for use via ssh, if you consider that connection could be disrupted during attack.
Answering to your second comment, as i saw it after have typed the first part:
I was going to port it to tmux for my own use anyway, so I will try my best, but at some point I will need a help with it. For now i can't see how to manage switch to tmux from your initial terminal in the middle of the script's work. It seems that without rebuilding whole structure of the script the only way to do it is to call airgeddon.sh from external script let's say "airgeddon_tmux.sh".

**Comment by OscarAkaElvis** [comment]
Ok, so fork it and do it on your own... as you wish. If you achieve something solid mail me in order to try to organize something for airgeddon. Closing this.

Thank you for your interest and suggestion. Regards.

**Comment by kand617** [comment]
This script would be awesome if tmux was an option. 
My use-case is that I can SSH in to my raspberry pi and run an evil twin attack

Alternatively I could use VNC and then run airegeddon, but I wont be able to exit the ssh session.
Any thoughts?

**Comment by OscarAkaElvis** [comment]
This is an open project. If somebody is able to do it using tmux as alternative is welcome!

**Comment by v1s1t0r1sh3r3** [comment]
This is finally to be developed as you can see on this other issue: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/134
