### ISSUE TITLE
Did it was tested on mac os 

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [v1s1t0r1sh3r3/airgeddon#150]
Did it was tested on macos or an spetial verison for macos ?

**Comment by v1s1t0r1sh3r3** [comment]
This script is compatible with Linux as you can see at wiki documentation: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility

Anyway, it was tried to be used on Mac OSX using Docker but is not fully working yet. That is on alpha phase. Because a custom kernel should be compiled. More info here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker%20Mac%20OSX
