### ISSUE TITLE
How graphically customize the captive portal?

### ISSUE THREAD

**Issue by waidoshoruda** [v1s1t0r1sh3r3/airgeddon#168]
#### What is your airgeddon version?

8.11

#### What is your Linux O.S. and which version?

Kali Linux 2018.2

#### Which is the chipset of your wireless card?

Ralink RT3070

#### Describe the issue and the steps to reproduce it

Hi,
there's a HOWTO on "How graphically customize the captive portal"? Which template files to edit.
The current captive portal is pratically "unusable". It does not fool anyone.

Thanks (especially for your project)

**Comment by v1s1t0r1sh3r3** [comment]
The captive portal is fully working and it "fool" tons of people, believe me.... anyway, you are free to customize it. If you look into the code, you'll see that during an attack, all the captive portal website is created inside /tmp/www directory. You can copy this files, modify it, the html, the js, css, put images or whatever you need to trick in order to create a more tailored attack. So after creating AP during the attack, you should copy your customized files into this /tmp/www dir.

Bear in mind that the files are deleted after the attack, so if you have a customized captive portal, keep a copy of your files. Closing.
