### ISSUE TITLE
Cannot install ruby-rubydns using the command from bettercap tips

### ISSUE THREAD

**Issue by marvic2409** [v1s1t0r1sh3r3/airgeddon#178]
Here is the errors:

(Reading database ... 227990 files and directories currently installed.)
Preparing to unpack bettercap_1.6.2-0parrot1_all.deb ...
Unpacking bettercap (1.6.2-0parrot1) over (1.6.2-0parrot1) ...
dpkg: dependency problems prevent configuration of bettercap:
 bettercap depends on ruby-rubydns (>= 1.0.3); however:
  Package ruby-rubydns is not installed.

dpkg: error processing package bettercap (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 bettercap

**Comment by v1s1t0r1sh3r3** [comment]
Follow the instructions on wiki to install the dependencies. Everything is explained there.

**Comment by marvic2409** [comment]
I followed the wiki instructions and it gave a bunch of errors when installing the dependencys. At first the install errors were: sudo dpkg -i bettercap_1.6.2-0parrot1_all.deb
Selecting previously unselected package bettercap.
(Reading database ... 227666 files and directories currently installed.)
Preparing to unpack bettercap_1.6.2-0parrot1_all.deb ...
Unpacking bettercap (1.6.2-0parrot1) ...
dpkg: dependency problems prevent configuration of bettercap:
bettercap depends on ruby-em-proxy (>= 0.1.8); however:
Package ruby-em-proxy is not installed.
bettercap depends on ruby-eventmachine; however:
Package ruby-eventmachine is not installed.
bettercap depends on ruby-network-interface (>= 0.0.1); however:
Package ruby-network-interface is not installed.
bettercap depends on ruby-rubydns (>= 1.0.3); however:
Package ruby-rubydns is not installed.

dpkg: error processing package bettercap (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
bettercap


But then I installed them manually and the only one that its not detecting is rubydns.

**Comment by marvic2409** [comment]
Any Help?

**Comment by v1s1t0r1sh3r3** [comment]
You are not following the instructions. Follow them step by step. It's very easy to perform the downgrade of bettercap. The error you put say that you are trying to install bettercap without the dependencies. First install the dependencies.
 
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Bettercap%20Tips

**Comment by v1s1t0r1sh3r3** [comment]
I'm going to close this issue for the following reasons:

1. You didn't filled up the issue template, so we don't know your O.S. or any other helping info.
2. This issue is not related to airgeddon. Probably you have some kind of mess with your dependencies. 

Anyway, I can tell you before closing it a couple of advices. Try it on a clean install or over a new virtual machine to test, you'll see it's an easy task. Or maybe you should try to install the dependencies one by one... for example, first uninstall bettercap `apt remove bettercap`, then `apt install ruby-net-dns`, then `apt install ruby-network-interface`, etc, etc. Closing.

**Comment by OscarAkaElvis** [comment]
Yeah, I saw that there are some problems on some repos. For example on Parrot repos (I must guess you are using Parrot Linux because you are not providing any info).

I already reported this to parrot staff (before your post). Anyway, what do you want airgeddon staff to do? Do you think we control the repos of the Linux distributions? Why the people when is not able to install something due the lack of packages on repos comes here to tell it instead of reporting to the people managing that repos? misteries of life... 👽

**Comment by OscarAkaElvis** [comment]
Check this... maybe could save some lifes:

https://github.com/v1s1t0r1sh3r3/airgeddon_deb_packages
