### ISSUE TITLE
AP mode not enabled

### ISSUE THREAD

**Issue by azamet90** [v1s1t0r1sh3r3/airgeddon#188]
everything is okay on my wlan0 which is intel wlan but on my alfa ACH model only the AP mode is not working what is the problem here? i love your app but i want to use it on my wifi adapter because of power of it can you pls help me about it? is this a bug or my fail?

**Comment by azamet90** [comment]
sorry for posting again the other problem is like i said it is fully working on internal intel wifi which is i dont like because of the power but the script is kicking no one out from the target wifi so how will this attack succesfull then if no one is disconnected it is only disconnecting for few seconds on capturing handshake i did tryed to kick out users with my external usb wifi adapter but if i try it and give the target mac address the fake AP is automaticly destroyed too :D sorry for my bad english and noob questions sir

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, everything here smells like n00b questions. Don't worry, we are here to help but in this way is very hard.

1. You didn't filled out the issue template... now we must lose time asking back to you about the details of your problem.
2. Your question is too broad. You are saying about the AP just "it doesn't work", but in order to understand what is happening we need all the details.
3. About the DoS... nothing is 100% effective. Maybe one clients are down, maybe others don't. Maybe your AP is not vulnerable to the attack. Maybe it's related to your chipset, etc. Hard to know and with this poor information you provide even harder.

So... I'll close this issue due lack of information. If you want to be helped here try to be sure that your problem is an airgeddon issue. Fill the template, put all the required data (airgeddon version, O.S., chipset, exactly the menu options you are using, put screenshots if needed, read the contributing policy for issue creation, etc.). And remember, choose wisely how to explain your problem because here we are to try to help and improve airgeddon, but we are not a wireless problems helpdesk support. Closing.

**Comment by azamet90** [comment]
thank you for answering so fast and sorry that i need ask another question which is very noob again :D 
can you pls help me to send you that informations you need?

just tell me which command i need to put to terminal shortly and i post it here very quickly
