### ISSUE TITLE
WPS Blank Pin (or Null Pin) Attack with Reaver

### ISSUE THREAD

**Issue by mrochaaa** [v1s1t0r1sh3r3/airgeddon#190]
Maybe good add WPS Blank Pin Attack with Reaver

**Comment by v1s1t0r1sh3r3** [comment]
At last (so much time passed!!) I have a vulnerable router to test this null wps pin attack. So I reopened this in order to implement it in a future version... It will be added in v9.20

The attack is available (for now) only for reaver. I written in bully's github to see if we can implement it also in bully: https://github.com/aanarchyy/bully/issues/14

**Comment by v1s1t0r1sh3r3** [comment]
This has been already added. It will be released as I said before in v9.20. Closing.
