### ISSUE TITLE
Menu for pcap auto convertion

### ISSUE THREAD

**Issue by mrochaaa** [v1s1t0r1sh3r3/airgeddon#192]
More one, seem the other, but is different, see...

airgeddon can add an option so, when you capture an handshake or pmkid, in the end show an menu like:

Crack or Convert output?

1- Hashcat format
2- John the Ripper format (wpapcap2jhon dependence, optional)
3 - Keep in Pcap format
4- Crack it now!

Because most users capture to convert after to JTR or Hashcat

**Comment by OscarAkaElvis** [comment]
airgeddon is managing the transformation to hashcat in all of its versions and it cracks the captured handshakes using aircrack and hashcat. John the ripper is for now out of scope for the handshake cracking on airgeddon. I can tell you that on the next v9.0 (which will have wpa/wpa2 enterprise networks attacks) the captured hashes will be able to be decrypted using john the ripper (in addition to hashcat and asleap).

As we said in other issue opened, PMKID stuff will be probably implemented in the future based on aircrack 1.4 . But the point of airgeddon is not to perform transformations between formats. airgeddon will do only the needed transformations to do something with the captured stuff. Any new option will use a different program and it imply more dependencies so we try to minimize that in order to require just the minimum needed stuff.

Thanks for your continuous suggestions. It seems you are a real enthusiast and we appreciate that, but I must say we also accept pull requests in addition to the suggestions. :smile:
