### ISSUE TITLE
shortly nothing is working :D

### ISSUE THREAD

**Issue by azamet90** [v1s1t0r1sh3r3/airgeddon#195]
so i did reinstall kali linux and install the fluxion for testing and was working perfect but on your app first problem is it is deadly slow for finding AP it is not catching handshake AP mode is not enabling :D you know my version of kali of your application which i have i give up with this app if you still think problem is on me it is your problem bro have a nice day

**Comment by v1s1t0r1sh3r3** [comment]
Oh my god... what is the point of openning this issue? You didn't followed (again) the issue rules. You didn't fillled the issue template, etc... Bear in mind that every time you open an issue, a mail is sent to all the people using the "watch" over this repo. So you are a right now a little spammer for a lot of people. Please avoid to open useless issues.

If another software is working for you, good for you. Use it and leave us in peace. We already told you the reason of your problem (hostapd and chipset incompatibility). Probably other software is using airbase to create AP instead of hostapd which is better for your card, I don't know, never used Fluxion but I heard is a good software.

Closing this and locking to avoid more "spam". If you don't stop writing here I'll block you from the repo. You left us no choice. Good luck.
