### ISSUE TITLE
Ask for password if try to navigate

### ISSUE THREAD

**Issue by marcoReda** [v1s1t0r1sh3r3/airgeddon#197]
#### Describe the feature or compatibility enhancement and involved versions if apply
I'm referring to "Evil Twin attack with captive portal": I'd like to propose a feature that ask for password when the user press "use this network as is"; infact in the actual situation, if you don't insert the password and you try to navigate you simply face a "deadlock" situation, which can be unlocked only deleting the fake network and re-connecting to it.

#### What are the benefits of adding this?
Encourage users to insert the password

**Comment by v1s1t0r1sh3r3** [comment]
I'm not understanding what you propose. Once the user clicks into the fake network (this part is needed and can't be avoided), the captive portal is detected as captive portal by the browsers and if the user clicks it goes automatically to it. Then the form for the user and password is asked and you'll get it if the user introduce it.

Not sure what is for you "use this network as is"... because you must think there are a lot of systems and a lot of browsers... I tested it in a lot of them and is working fine. If you connect to the fake network using an Android device for example, the captive portal is shown quickly. Not sure what you are talking about for the "deadlock" situation. Be more specific, browser, device, pc? mobile? android? ios? etc. Anyway, there is nothing more we can do I think. Please try it using more systems, more mobile devices, you'll see what I'm talking about. It is working fine for the most of them but as I said, I think it's impossible to get it fully working for all of them but right now is working fine for almost all.

**Comment by marcoReda** [comment]
Good evening,

first of all thanks for the immediate reply. What I'm going to say has been tested on Android Marshmallow, Nougat and Oreo, I would say "quite exhaustive" as case studies. Perhaps I expressed badly and apologize for this; what happens (and maybe I make some mistakes, but in that case I beg you to report it) is that once the user is redirected to the login page, if he decides to don't enter the password, he can (from the notification bar that slides down from the top) select "use this network as it is"; statistically I tested the procedure on a dozen people and instinctively they all have opted for this choice; when this happens, there is no longer any type of redirection or password entry required! If the user opens the Facebook or Chrome app, simply the "no network message" is notified, without asking to enter the password in order to browse again.

**Comment by v1s1t0r1sh3r3** [comment]
Yeah but that is not a web message... that is a push notification of Android system. There is nothing we can do here. And if they press "no" they are not accepting to work with the network.... nothing to do.

Then if they open apps, the portal have no effect over apps... it is a web page, so it will be opened only if they open a browser and try to surf any web on internet. Nothing to do here again from the perspective of creating a captive portal my friend! sorry, but what you are asking for can't be done on bash creating a web page. Anyway, thanks for your suggestion. Closing.
