### ISSUE TITLE
/opt/airgeddon/airgeddon.sh: line 8700: /tmp/wps.txt: No such file or directory

### ISSUE THREAD

**Issue by isgerasin** [v1s1t0r1sh3r3/airgeddon#204]
Hello! I have some troubles with airgeddon. I hope it isn't my stupid mistake :)

#### What is your airgeddon version?

Docker version 18.06.1-ce
v1s1t0r1sh3r3/airgeddon:latest

#### What is your Linux O.S. and which version?

Ubuntu 16.04.5 LTS

#### Which is the chipset of your wireless card?

Intel Corporation Device 24fd (rev 78)

#### Describe the issue and the steps to reproduce it

Error "/opt/airgeddon/airgeddon.sh: line 8700: /tmp/wps.txt: No such file or directory" shows up when i choosing option 4 in wps attacks menu (4. Explore for targets (monitor mode needed)).

docker run:
sudo docker run --rm -ti --name airgeddon --net=host --privileged -p 3000:3000 -v /home/master/io:/io -e DISPLAY=:0 v1s1t0r1sh3r3/airgeddon

![airgeddon_bug](https://user-images.githubusercontent.com/9885445/50472686-c033ea80-09b1-11e9-8ef9-ae099af8e33c.png)

Thanks

**Comment by v1s1t0r1sh3r3** [comment]
I think that your problem is related to the DISPLAY stuff. I guess that on loading, the container is not connecting correctly to your DISPLAY in order to open the needed to work xterm window. I guess that a similar problem will happen to you performing a standard scan (non-wps scan) on any other submenu. I have some questions:

Once launched, is airgeddon able to detect your screen resolution? I guess that the answer is no. Can you put a screenshot of this part?
Are you using X Window System or Wayland?
If you perform this command, what do you get?: `env | grep DISPLAY`
Did you tried instead of setting on command line DISPLAY=:0 using what wiki recommends? I mean: `-e DISPLAY=$(env | grep DISPLAY | awk -F "=" '{print $2}')`

**Comment by isgerasin** [comment]
1) You are quite right.
![2018-12-27 13-19-19](https://user-images.githubusercontent.com/9885445/50476673-deedad80-09c0-11e9-89bf-dbff77800de5.png)
2) I am using  X Window System

3) # env | grep DISPLAY
DISPLAY=:0

4) Yes, I tried both variants

**Comment by isgerasin** [comment]
I tried  "xhost +". All working, thanks)

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, xhost stuff is adviced on wiki. It is on docker section "linux tips". Glad to be working for you.
