### ISSUE TITLE
Having error with WPS.

### ISSUE THREAD

**Issue by sorceror2k5** [v1s1t0r1sh3r3/airgeddon#206]
******************************** Select target ********************************* 

  N.         BSSID      CHANNEL  PWR   LOCKED  ESSID 
------------------------------------------------------- 
  1)       -     0%         
  2)       -     0%         

------------------------------------------------------- 
Select target network: 
>

**Comment by sorceror2k5** [comment]
WPS Attack Menu > Explore Targets

**Comment by OscarAkaElvis** [comment]
Sorry but it is unclear what is the problem. You didn't filled correctly the issue creation template in order to know a lot of needed data (version, O.S., etc). Is hard to guess but maybe if you are referring that the power is not shown on the selection network screen I must say that is not related to airgeddon. Some cards are not getting well this info when using wash (included on reaver package). Closing.
