### ISSUE TITLE
running airgeddon in a non GUI system

### ISSUE THREAD

**Issue by 4ntil0l** [v1s1t0r1sh3r3/airgeddon#214]
### What is your airgeddon version?
latest
### What is your Linux O.S. and which version?
debian 8 testing 
#### Describe your question as detailed as possible
so emm i have a pc which has 2GB ram running xfce  and sometimes i just shut the x window server and run my stuff via sh too save ram
when i tried to run airgeddon on only sh (no gui) `cos there was no x window server running it closed the program and i was kinda disappointed cos some features they just dont need new terminal like the whole thing is just needs not x window server i think you guys can change the code and make it run on non gui systems too ( like cracking a password and stuff )
or just change the code in a way that when there is no x window server it just run the programs in background and show the result

**Comment by v1s1t0r1sh3r3** [comment]
Hi, this was already discussed some times:
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/160
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/138
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/134

This what you propose is a major change. Maybe in the future tmux could be used instead of xterm or maybe a system can be done to change this as an option but for now is not planned to be developed. Thanks anyway for your suggestion. Regards.

Closing.

**Comment by v1s1t0r1sh3r3** [comment]
This is finally to be developed as you can see on this other issue: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/134

**Comment by 4ntil0l** [comment]
Nice tanx
