### ISSUE TITLE
DoS pursuit mode without monitor mode

### ISSUE THREAD

**Issue by KeyofBlueS** [v1s1t0r1sh3r3/airgeddon#216]
Hi, thanks for this fascinating tool!

When performing a deauthing attack, in order for the DoS pursuit mode to work, actually we need a second wireless card in monitor mode.
I was thinking that if a wireless card do not support monitor mode for any reason (like mine, that cause airgeddon DoS pursuit mode to completly fault), we can choose to check the channel change by simply scanning for the target every n time and... check the channel. What do You think about it?

I wrote a proof of concept bash script for that, attached.

If implemented, Airgeddon should give user the choose of monitor mode or scan.

Best regards!

[channel_check.sh.txt](https://github.com/v1s1t0r1sh3r3/airgeddon/files/2756186/channel_check.sh.txt)

**Comment by v1s1t0r1sh3r3** [comment]
Thanks for your suggestion but the requirement of needing two monitor mode compatible cards is due a physical limitation. One card has only one antenna, and one antenna means that it can operate only in one channel at a time. So... while one card is performing the DoS, the other card is scanning all the other channels performing channel hopping looking for the target AP.

With your method and only one card is not possible to perform two tasks at the same time over two different channels... while you scan, your DoS attack is interrupted. So that's the reason because the requirement of two compatible to monitor mode cards was set. Is a low price IMO for that interesting feature. Evil Twin with DoS pursuit mode is looking for 100% of effectiveness. Anyway, thanks for your effort writing a script and for your suggestion. Closing.

**Comment by KeyofBlueS** [comment]
Thanks for your review @v1s1t0r1sh3r3 , but I don't mean using only one card. Instead I mean using first card in monitor mode to perform the dos attack, and the second (non monitor capable) card to check channel change simply by scanning. Do you think is it possible?

**Comment by OscarAkaElvis** [comment]
You are right, this can be done using iwlist in managed mode, but nowadays is very rare to find a non-monitor compatible card. I think it doesn't worth the time of developing this, sorry. But to answer your question, yes, it could be done.

**Comment by ChillVibesMushroom** [comment]
doesn't airodump-ng already channel hop? I want to understand this more  and get some insight on how to use this script I have two alfas one is 2.4 one is 2.4/5.0 and i have an internal supporting 2.4/5.0 which is meh 
I'm at home right now about to rest after eating from the Asian Cafe God I love that place it always makes me want to nap guys.

1) both cards need to support the same frequency
2) one card is generating traffic and we can deauthenticate using the aircrack-ng suite
I under stand this part now
*I thought airodump-ng had a --cswitch method to channel hop for us but if this doesn't work 
3) I have a second nic where I just edit
INTERFACE=wlan1
TARGET=AB:01:CD:23:EF:45
TIME=30

and it doesn't even have to be in monitor mode? I just run the script and somehow it connects with wlan0mon???

**Comment by OscarAkaElvis** [comment]
To know how DoS pursuit mode works. Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-dos-pursuit-mode-exactly

I recommend you to use v11.20 which at the moment of writing is not released yet, but you can get it from Dev branch. It has improvements about this.

**Comment by ChillVibesMushroom** [comment]
During a standard Evil Twin attack, your wireless physical card is split into two logical interfaces. One to create the fake Access Point and another to perform the DoS in monitor mode. During the attack, if the target AP is configured in channel "Auto" and if the victim resets it due to lack of connectivity resulting from the DoS attack, once rebooted, it may switch to another channel rendering our attack perform DoS over a wrong channel and the victim re-establish the connectivity.

Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
Linux kali 5.18.0-kali5-amd64 https://github.com/aircrack-ng/aircrack-ng/issues/1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
Aircrack-ng 1.7 - (C) 2006-2022 Thomas d'Otreppe
global
country US: DFS-FCC
(902 - 904 @ 2), (N/A, 30), (N/A)
(904 - 920 @ 16), (N/A, 30), (N/A)
(920 - 928 @ 8), (N/A, 30), (N/A)
(2400 - 2472 @ 40), (N/A, 30), (N/A)
(5150 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
(5250 - 5350 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
(5470 - 5730 @ 160), (N/A, 24), (0 ms), DFS
(5730 - 5850 @ 80), (N/A, 30), (N/A), AUTO-BW
(5850 - 5895 @ 40), (N/A, 27), (N/A), NO-OUTDOOR, AUTO-BW, PASSIVE-SCAN
(5925 - 7125 @ 320), (N/A, 12), (N/A), NO-OUTDOOR, PASSIVE-SCAN
(57240 - 71000 @ 2160), (N/A, 40), (N/A)

This is the issue I am having sometimes not all the time and it's mind boggling I even went all the way to re installing the drivers for kali
which never had to be done in the past my network bro is too good...

should I use the --cswitch method and choose a different channel hopping method idk whats going on





https://user-images.githubusercontent.com/99580833/229302529-a6094a09-905f-47dd-a8db-5cd663627cd9.mp4

**Comment by OscarAkaElvis** [comment]
But .... You are not using airgeddon in the video. To discuss offtopic questions, please join to our Discord server. Link is in the contact section at wiki.

In addition, I can see you have a crappy WiFi card. RTL cards are not good for WiFi hacking. Probably your card doesn't support VIF. Please. Read in wiki FAQ what VIF is, and check the list of the recommended cards: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets


Most of the RTL cards are blacklisted for WiFi hacking.

**Comment by ChillVibesMushroom** [comment]
> But .... You are not using airgeddon in the video. To discuss offtopic questions, please join to our Discord server. Link is in the contact section at wiki.
> 
> In addition, I can see you have a crappy WiFi card. RTL cards are not good for WiFi hacking. Probably your card doesn't support VIF. Please. Read in wiki FAQ what VIF is, and check the list of the recommended cards: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
> 
> Most of the RTL cards are blacklisted for WiFi hacking.

I do have this type of card

Alfa AWUS036ACM

but when I plug into kali I get a zsh error and I can't even use my terminal and the next time I log into kali it wipes my OS then I have to restart kali in order to get my saved folders back :(

I was thinking about making everything read and writeable in my OS so that when I connect the USB there aren't any errors I noticed if I start the OS with the adapter connected there aren't any issues is that a kali bug?

its bad to start an OS as read and write correct that leaves us open to attacks lol

**Comment by ChillVibesMushroom** [comment]
Actually I'll ask on the github page and not bother you guys and if anyone needs the fix Ill just update it here and change topic name to relate to that fix for anyone wanting to learn how to fix it. <3

**Comment by OscarAkaElvis** [comment]
If you read about that adapter in our wiki (https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets) you'll see that it is messed up while used in virtual machines, no matter the OS. So use it only in native linux or you'll have problems.

Regarding your last comment. Please, don't do that. If you want to share your knowleged, findings or keep asking stuff, join Discord server. Don't use Github issues for that please. You'll find the Discord invitation link at wiki in contact section.

**Comment by Obigold** [comment]
tp-link WN722n v2 has its own issues of constantly disconnecting or unresponsive or idle for no reason. I don't know if it is compatibility issues or driver issues which i think i installed perfectly.
I have to keep unplugging and plugging it before i can perform any attack with it.
