### ISSUE TITLE
mac spoofing even if not selected

### ISSUE THREAD

**Issue by KeyofBlueS** [v1s1t0r1sh3r3/airgeddon#218]
#### What is your airgeddon version?

8.12

#### What is your Linux O.S. and which version?

Debian sid

#### Which is the chipset of your wireless card?

Ralink corp. RT2561/RT61 802.11g PCI

#### Describe the issue and the steps to reproduce it

In Evil Twin Attack, even if mac spoofing is not selected, the evil twin ap created has the same bssid than the real one, and the deauthing attack will affect the evil twin ap also.
My workaround was to hardcode a different mac (random) in airgeddon.sh, function set_hostapd_config, line 6165 from

	echo -e "bssid=${et_bssid}"

to example

	echo -e "bssid=07:23:67:72:52:60"

I noticed that after the card was set in monitor mode, checking with ifconfig, the mac changes from

ether "random mac address"  txqueuelen 1000  (Ethernet)

to

unspec 00-0C-F6-39-E3-8A-30-3A-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

maybe the problem relies here

**Comment by OscarAkaElvis** [comment]
No my friend.... creating Evil Twin, the Fake AP has no exactly the same BSSID as target. As you said if the Fake AP has exactly the same BSSID as target, the DoS attack is going to affect also to our Fake AP and this is not the case. airgeddon is creating a very very similar BSSID but not the same. It changes only one byte in the middle because first three pairs are the vendor and the last pairs maybe could be memorized by the victim, so we decided to change only one of the bytes from the middle of the BSSID and the user will be tricked like you now :smile:

Check the code, you'll see that line 6159 (we are talking about v8.12 or the line will be other), there is a `${different_mac_digit}` in the middle so it is done. The fake AP has a different BSSID. Closing.

**Comment by KeyofBlueS** [comment]
Unless... I was so unlucky that:
	different_mac_digit=$(tr -dc A-F0-9 < /dev/urandom | fold -w2 | head -n 100 | grep -v "${bssid:10:1}" | head -c 1)

returned the same value as in the original :|

**Comment by OscarAkaElvis** [comment]
No my friend, that is not possible. This line is generating a char ALWAYS different than the original. Do the tests yourself.

As you can see, this example mac has an `8` in the position we are going to change. If you launch this it spites an eight: `var="12:34:56:78:90:12" ; echo "${var:10:1}"`

If you check the code, the randomization is done by the line I told you. It is generating something always different than `8`: `var="12:34:56:78:90:12" ; tr -dc A-F0-9 < /dev/urandom | fold -w2 | head -n 100 | grep -v "${var:10:1}" | head -c 1`

The `grep -v` is doing the trick excluding the same char (8 in this case).

So it is not possible to have exactly the same mac address... there must be a mistake.

Regarding your other problem.... you said that even with different BSSID, the DoS is affecting you. I can't tell you why because I don't have any data about what kind of Dos are you launching. Maybe you are launching one ESSID based instead of BSSID based and is affecting you anyway or I don't know. Regards.

**Comment by KeyofBlueS** [comment]
Yes I was wrong, it's impossible to return the same value as you said, I noticed it, came here to tell...

The attack was with Aireplay, BSSID based. Anyway this is really not a problem to solve for me personally. Just reported here to contribute.

Thanks
