### ISSUE TITLE
Wrong interface name on evil-twin attack

### ISSUE THREAD

**Issue by underscrew** [v1s1t0r1sh3r3/airgeddon#225]
#### What is your airgeddon version?

v9.01

#### What is your Linux O.S. and which version?

raspbian with current stable re4son-pi-kernel
```root@raspberrypi:/home/pi# uname -a
Linux raspberrypi 4.14.93-Re4son-v7+ #1 SMP Thu Jan 24 12:44:19 AEDT 2019 armv7l GNU/Linux
```

#### Which is the chipset of your wireless card?

rtl8812au using the [working driver](https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20).

#### Describe the issue and the steps to reproduce it

Evil-Twin attack on 5Ghz opens a hostapd window with the following message:
```
Configuration file: /tmp/ag.hostapd.conf
Could not read interface You already have flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=You already have disabled_11b_rates=0
Could not read interface You already have flags: No such device
nl80211 driver initialization failed.
You already have: interface state UNINITIALIZED->DISABLED
You already have: AP-DISABLED 
hostapd_free_hapd_data: Interface You already have wasn't started
```

Looking at `/tmp/ag.hostapd.conf`, i can see:

```
interface=You already have a wlan2 device but it is NOT in station mode.
driver=nl80211
ssid=XXXXX
bssid=XX:XX:XX:XX:XX:XX
channel=2
```
Which is very weird.

Deauth using mdk3 also seems to be getting the wrong interface name:
```
Interface mon: 
ioctl(SIOCGIFINDEX) failed: No such device
```

This is confirmed looking the process:

```
$ ps -ef | grep mdk3
root      4328  1213  1 04:18 pts/0    00:00:12 xterm -hold -bg black -fg red -geometry 93x16+0-0 -T Deauth -e mdk  mon d -b /tmp/"bl.txt" -c 104
```
The right device should be, in this case, wlan2.

Thus, no deauth happen nor AP is created.

I manually tested mdk3 and hostapd (using the `hosapd.config` below) and both are working properly.
```
# Basic configuration
interface=wlan2
ssid=WiFi_SSID
channel=5

# WPA and WPA2 configuration
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=Some_PassWord
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP

# Hardware configuration
driver=nl80211
ieee80211ac=1
hw_mode=g
```

change `hw_mode = a` in order to create a 5Ghz AP.

**Comment by OscarAkaElvis** [comment]
Hello, I worked flawlessly many times using Raspbian... your problem is related to your wireless card driver and neither to Raspbian nor airgeddon. It seems that for some reason, it can't read correctly the interface name probably on name change. This is a recurrent issue opened here:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/203
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/185
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/100

And this is more interesting. On it you can find some interesting link: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/201

I can recommend to you to use the package available on repositories which works flawlessly with that card. It seems that that driver is not printing the outputs in a standard way. The package can be installed by apt and it is called `realtek-rtl88xxau-dkms`, (alt least it is available on Kali and Parrot repositories... to be honest not sure now if it is available on Raspbian repositories). If possible, give it a try.

**Comment by xpz3** [comment]
For raspbian you need to compile the drivers depending on rasp version. It's detailed in the github page the OP provided.
