### ISSUE TITLE
how to remove unwanted interfaces

### ISSUE THREAD

**Issue by jepunband** [v1s1t0r1sh3r3/airgeddon#227]
#### What is your airgeddon version?

9.1

#### What is your Linux O.S. and which version?

Kali Nethunter

#### Which is the chipset of your wireless card?

Atheros

#### Describe the issue and the steps to reproduce it

Hi  airgeddon works fine on nethunter. I just wanted to know how to remove or disable some of the unwanted interfaces detected by airgeddon. Like in the picture.
![screenshot_20190224-112218](https://user-images.githubusercontent.com/46950575/53295878-cfafa280-383f-11e9-8cb7-08639a2ec9c0.png)

**Comment by v1s1t0r1sh3r3** [comment]
You can't remove the unwanted interfaces... why do you want to remove the interfaces? they are the interfaces present on your phone. I must say this is completely normal in a phone.

If airgeddon is working fine there is no problem, just ignore them. Select your wlan interface and that's all you need. This is not a problem. arigeddon can't know if you want an interface or know in order to show it, the way you can say to airgeddon you want an interface is selecting it. This is completely out of scope of airgeddon. I insist, this is completely normal in a phone. My phone has similar interface list.
