### ISSUE TITLE
How to make airgeddon stop redirecting 1 particular site

### ISSUE THREAD

**Issue by lilbigmed** [v1s1t0r1sh3r3/airgeddon#228]
#### Is your question related to any concrete technology?
DNS
#### Describe your question as detailed as possible
I am trying to add an exception site that won't get redirected to the captive portal.What would be the best way to achieve that in this program?

**Comment by v1s1t0r1sh3r3** [comment]
What? the purpose of captive portal is to redirect everything to the captive portal. Maybe you can try to configure dnsspoof with a custom config file in order to avoid the "DNS blackhole" which is default configuration to set some domains to be redirected where you want. But this is absolutely out of scope of the airgeddon issues. Closing.
