### ISSUE TITLE
hostapd issue in manjaro

### ISSUE THREAD

**Issue by takobaba** [v1s1t0r1sh3r3/airgeddon#229]
#### What is your airgeddon version?

airgeddon 9.01

#### What is your Linux O.S. and which version?

Manjaro - Illyria 18.0.3
Kernel 4.19.24-1

#### Which is the chipset of your wireless card?

ar9462 Atheros

#### Describe the issue and the steps to reproduce it

When I choose the evil twin attack captive portal, as soon as the hostapd starts i get an error on the script terminal, "Interface changed its name while setting in managed mode.". I dont understand this error because the interface was already in monitor mode. confusing.

Then on the hostapd terminal, I get interface initialize failed with Invalid BSSID item. I have read about similar issues all pointing to network manager and my Network manager is already stopped.

Any help appreciated, let me know if any further info is needed.

Regards,

**Comment by v1s1t0r1sh3r3** [comment]
To perform evil twin attack using only one adapter, airgeddon is splitting your physical interface into two different logical interfaces. One in mode managed to perform the hostapd stuff creating AP and the other in monitor mode to perform DoS part. So is normal... anyway, the message you are saying is not an error, is a warning (yellow=warning, red=error). Anyway, try to launch manually outside airgeddon, just to test `airmon-ng check kill`.

Yeah please, put screenshots... is your evil twin working fine first time and failing only on second time? not sure to understand what is happening.

**Comment by takobaba** [comment]
It Never worked.

Okay but the invalid bssid item and interface initialize failed errors on ap terminal are not normal? 

When I do airmon-ng check kill, it kills 2 avahi-daemon s. Should I run airmon-ng check kill right when I start the script or Timing is not that important?

**Comment by OscarAkaElvis** [comment]
In first place I must say you are using an unsupported Linux (unsupported by airgeddon). Anyway, we'll try to debug your problem. You are going to be more specific please. Let's suppose that your wireless card name is `wlan0`:

 - Is your card compatible to airmon? This is important. To know that, just launch (completely out of airgeddon) `airmon-ng wlan0 start` and put a screenshot (a screenshot please, or a copy/paste of the output, not on your words).

Try (out of airgeddon) to run hostapd. For that, your card must be in managed mode (this is important). Save this as a config file (any name) and then launch `hostapd yourconfigfile`:

```
interface=wlan0
driver=nl80211
ssid=test
bssid=00:00:00:03:00:11
channel=1
```

Let's see if the hostapd is up. If is not working, retry after launching `airmon-ng check kill`. Let us know the results.

**Comment by takobaba** [comment]
Thanks for the reply. here are the results

````
[tarik-pc tarik]# airmon-ng start wlp0s20u1


PHY	Interface	Driver		Chipset

phy2	wlp0s20u1	ath9k_htc	Qualcomm Atheros Communications AR9271 802.11n

		(mac80211 monitor mode vif enabled for [phy2]wlp0s20u1 on [phy2]wlp0s20u1mon)
		(mac80211 station mode vif disabled for [phy2]wlp0s20u1)

[tarik-pc tarik]# airmon-ng check kill

[tarik-pc tarik]# cat hostapd_test.cfg 
interface=wlp0s20u1mon
driver=nl80211
ssid=test
bssid=00:00:00:03:00:11
channel=1
[tarik-pc tarik]# hostapd hostapd_test.cfg 
Configuration file: hostapd_test.cfg
Using interface wlp0s20u1mon with hwaddr 00:00:00:03:00:11 and ssid "test"
wlp0s20u1mon: interface state UNINITIALIZED->ENABLED
wlp0s20u1mon: AP-ENABLED
````

to summarize

My wifi card is a monitor mode enabled one atheros chipset
and hostapd worked outside.

I just wanna note something I noticed and tested and verified:

````
[tarik-pc ~]# cat /tmp/ag.hostapd.conf 
interface=wlp0s20u1
driver=nl80211
ssid=antiques118
bssid=7C:26:64:F:EC:66
channel=1
````


this is the config file airgeddon generates and I get BSSID error. if you look at the F after 64 that should be 0F. And I ve tested it outside airgeddon and I get the same result. If I remove the zero on my test hostapd config file for the bssid this is what I get:

```

[tarik-pc tarik]# cat hostapd_test.cfg 
interface=wlp0s20u1mon
driver=nl80211
ssid=test
bssid=00:00:00:3:00:11
channel=1

[tarik-pc tarik]# hostapd hostapd_test.cfg
Configuration file: hostapd_test.cfg
Line 4: invalid bssid item
1 errors found in configuration file 'hostapd_test.cfg'
Failed to set up interface with hostapd_test.cfg
Failed to initialize interface
[tarik-pc tarik]# 

```

exact same error message as I am getting in the airgeddon. It proves that the mac address field generated by airgeddon without that leading zero is failing the hostapd. 

Now my question is, how can I force airgeddon to put the leading zero and generate correct format?

Let me know if anything is unclear or you need further information.

And I appreciate all the help and hardwork behind this.

**Comment by OscarAkaElvis** [comment]
Quite strange... because it is working flawlessly in other Linux distributions.... airgeddon is getting the bssid and then it switch one digit in the middle in order to avoid to be affected by its own DoS. It seems that part is not well done on your distribution. Let me check and I'll be back to here with the code and the commands that airgeddon is doing to do that and then we can do some tests. Thanks.

**Comment by takobaba** [comment]
yea I saw that bit in the airgeddon.sh. lovely code man haha thank you so much.

I m happy that we are able to at least identify the problem bit. It could be because of my distro manjaro, i m new on this distro too.

**Comment by rdcdt1** [comment]
try this for me it work (i had the same issue)
https://askubuntu.com/questions/928084/how-to-rename-wlp2s0-to-wlan0-in-ubuntu-17-04

**Comment by OscarAkaElvis** [comment]
Hi, first question. What is your bash version? Easy to get, launch this `echo ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}`

More stuff... this is the code of the operations done by airgeddon in order to set bssid on hostapd config file:

```
different_mac_digit=$(xxd -p -u -l 100 < /dev/urandom  | sed "s/${bssid:10:1}//g" | head -c 1)
et_bssid=${bssid::10}${different_mac_digit}${bssid:11:6}
```

As I explained before, it takes the ${bssid} from the victim and changes one of the digits for a random different one in order to avoid to be exactly the same bssid because if the bssid of the fake AP is exactly the same and on the same channel, the DoS is going to affect to the fake AP... so that is the reason of the small change.

Now, let's analyse very command on your Linux. Execute and put here the output of these commands:

`xxd -p -u -l 100 < /dev/urandom`

It should generate a random set of hex chars similar to this:

![image](https://user-images.githubusercontent.com/5803348/53372368-f6aac900-3952-11e9-8742-ed1c7528e8a8.png)

Now let's analyse the next step. Let's check if the sed command is working for you. Launch this on the console:

`bssid="00:00:00:00:00:00"; xxd -p -u -l 100 < /dev/urandom  | sed "s/${bssid:10:1}//g"`

The sed command is going to take a concrete position and is going to exclude it from all the generated chars... so, if we example bssid has all digits as 0, on your output should never be a 0. Like this:

![image](https://user-images.githubusercontent.com/5803348/53372433-22c64a00-3953-11e9-849e-ea0a24b7b9a0.png)

There is no zeros here... it seems is working fine... at least for all uf us. Can you put the output of your command?

And the last part, the `head -c 1` which is going to take only one... so at this point we have a random hex digit different than the original one. That's the summary of the first line of our code. This is unneded to be tested.

Now, let's analyse the second line. The point of the line is to create a var with the bssid but replacing one of the digits by the random generated. Launch this (this test is combining both lines in one to be launched on the console):

`bssid="00:00:00:00:00:00"; different_mac_digit=$(xxd -p -u -l 100 < /dev/urandom  | sed "s/${bssid:10:1}//g" | head -c 1); et_bssid=${bssid::10}${different_mac_digit}${bssid:11:6}; echo $et_bssid`

It should generate as shown on the below image always a different random hex char... if this is not working for you, here comes the problem! let us know what the hell is happening here on your linux.

![image](https://user-images.githubusercontent.com/5803348/53372226-9451c880-3952-11e9-965c-dd02e9c09f06.png)

I'm really curious where this is failing to you... it works on all the supported Linux listed here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility

Maybe we can do a change in order to make it to work in all the systems.

**Comment by takobaba** [comment]
ok here we go:

this is what I had to fix at the beginning:

``
[tarik-pc tarik]# different_mac_digit=$(xxd -p -u -l 100 < /dev/urandom | sed "s/${bssid:10:1}//g" | head -c 1)
bash: xxd: command not found
``

xxd doesnt exist. maybe this is the problem with the distro.

after I installed the xxd package using yaourt:

``
yaourt xxd
``

below all worked

```
different_mac_digit=$(xxd -p -u -l 100 < /dev/urandom  | sed "s/${bssid:10:1}//g" | head -c 1)
et_bssid=${bssid::10}${different_mac_digit}${bssid:11:6}

[tarik-pc tarik]# xxd -p -u -l 100 < /dev/urandom
DF65283ABF81965F001DE45C77945E1A1723FDB808E36F45C2EB35EDC29F
C1B62601BCE46FC01F6D1798AAE4C37657E735B600953ED4D671C0345E86
8CDD955C56299C42BAB1DAA02C8224F5FA623EB4182F3DD8F24DBB7A7319
B48CD2284D48BCB5EC20

[tarik-pc tarik]# bssid="00:00:00:00:00:00"; xxd -p -u -l 100 < /dev/urandom | sed "s/${bssid:10:1}//g"
3E7BC4DD43AC5D519E8464F9AC124FCF169877DDA2F8DE5C312E692C
E8F4E833F7911E6383F65B289ED3C4E64177197B5C39C1B868DED638
B9E693985B9878252EAD43DBA9349196F82858BB61E83ADC546DD4A738
DFD26C261221DECEA4

[tarik-pc tarik]# different_mac_digit=$(xxd -p -u -l 100 < /dev/urandom  | sed "s/${bssid:10:1}//g" | head -c 1)
[tarik-pc tarik]# echo $different_mac_digit 
4

[tarik-pc tarik]# bssid="00:00:00:00:00:00"; different_mac_digit=$(xxd -p -u -l 100 < /dev/urandom | sed "s/${bssid:10:1}//g" | head -c 1); et_bssid=${bssid::10}${different_mac_digit}${bssid:11:6}; echo $et_bssid
00:00:00:0D:00:00

```


ran the airgeddon and tested. 

After installing xxd package on manjaro it works. I believe installing vim or gvim would also fix it. weirdly on this arch linux distro manjaro there is no vim. 


thanks a lot for all the help.

**Comment by OscarAkaElvis** [comment]
Ok solved. Maybe we should add xxd as dependency for evil twin attacks to avoid this problem. Closing.

**Comment by OscarAkaElvis** [comment]
This is fixed for the next v9.10 , xxd is not needed anymore. It can be tested cloning the dev branch.

**Comment by darkhacker62615** [comment]
for me i have the xxd package but still doesnt works and the error is same

i typed all that commands. i didnt got any error. the commands work perfectly fine but when i use evil twin attack in airgeddon. everything works till the dhcp server window control window dns spoof winndow and all that opens. but the ap window says interface wlan0 wasnt started

![image](https://user-images.githubusercontent.com/68072809/87065543-986e4580-c22a-11ea-872a-f0b08a727641.png)

and when i typed the command
bssid="00:00:00:00:00:00"; xxd -p -u -l 100 < /dev/urandom | sed "s/${bssid:10:1}//g"
i get some zeros in between.

i think my wifi card adapter doesnt support ap mode but it does support monitor mode, managed mode and ibss mode.

when i type iw list i get these supported mode but not ap mode.

![](https://user-images.githubusercontent.com/5803348/53372433-22c64a00-3953-11e9-849e-ea0a24b7b9a0.png)

i am using ubuntu 20.04 LTS

plz help me fast.

**Comment by OscarAkaElvis** [comment]
You seems a little lost. This is not related to this closed issue.

1. The word "fast" on your message is out of place. We are not a support helpdesk where you pay for a service. Be careful with that kind of words for the next time, not only here.
2. We don't like n00b users with n00b nicks taking time to ask for "fast" help and who are not taking 10 secs to make one click to star our repo to support it but they take time to write asking for help.
3. If you need help, join the Discord channel to do further tests. Locking.
