### ISSUE TITLE
Fail deauth attack in evil twin captive portal

### ISSUE THREAD

**Issue by rusopro** [v1s1t0r1sh3r3/airgeddon#231]
#### What is your airgeddon version?
9.01

#### What is your Linux O.S. and which version?
4.19.0-kali1

#### Which is the chipset of your wireless card?

RTL8187L

#### Describe the issue and the steps to reproduce it

When i try the evil twin captive portal attack the deauth attack to retrieve the handshake works great but at the moment of deauth to capture the password dont send the deauth packets
![screenshot from 2019-03-01 01-08-59](https://user-images.githubusercontent.com/48113299/53615950-2eb64400-3bbf-11e9-964b-673b5dd83215.png)

**Comment by OscarAkaElvis** [comment]
Sorry but the process used to perform both DoS (handshake and evil twin) is exactly the same... so that makes no sense. The screenshot is not probing anything. This worked flawlessly since a lot of versions and there is no recent commits that could affect to it, so it seems some kind of user-side problem.

Please perform more tests before openning an issue because we are pretty sure that the DoS part is working fine. Closing.

**Comment by xpz3** [comment]
This sometimes happens if you are using aireplay-ng. Just try the mdk3 for deauthentication. It should work.
If this happens for mdk3, uninstall mdk3 and reinstall it. It should then work.

**Comment by rusopro** [comment]
Thanks i give ir a try and update this comment

**Comment by xpz3** [comment]
Thanks for updating the status. It will help others facing the same issue

**Comment by MrunalThakur** [comment]
I'm facing the same issue
airgeddon v10.30
Kali 2020.3
Intel corporation wireless-AC 9560

i tried installing mdk3 and switching from mdk4 to mdk 3 but i still have the same problem

**Comment by OscarAkaElvis** [comment]
Maybe you can try using another wireless card. As we said here... DoS is tricky. Not all APs are affected, not all clients are affected, not all type of attacks works the same always... if the environment is different, the type of attack may vary. Even it could be that some clientes are deauthed and others are not. In addition you need good signal, otherwise you'll not be able to success.

Join our discord channel for further help or discussion. Invitation link is on contact section at wiki.

**Comment by LeelaBhaskar-1515** [comment]
> Maybe you can try using another wireless card. As we said here... DoS is tricky. Not all APs are affected, not all clients are affected, not all type of attacks works the same always... if the environment is different, the type of attack may vary. Even it could be that some clientes are deauthed and others are not. In addition you need good signal, otherwise you'll not be able to success.
> 
> Join our discord channel for further help or discussion. Invitation link is on contact section at wiki.
