### ISSUE TITLE
"There is a problam with the selected interface"

### ISSUE THREAD

**Issue by packoa** [v1s1t0r1sh3r3/airgeddon#233]
**airgeddon version:**

the latest one , v9.01

**Linux O.S. and version:**

VMware - Other Linux 4.x or later kernel 64bit (tried also with debian 9)
Kali Linux 2019.1a

**Wireless card chipset:**

Realtek RTL8188EUS (TP-LINK TL-WN722N v3)

driver rtl8188eus v5.3.9:
https://github.com/aircrack-ng/rtl8188eus

**issue:**

![TUnotil](https://user-images.githubusercontent.com/48377582/54068279-cc89be80-4210-11e9-8066-6f22aabfcd83.png)

**more related info:**

![TUnotil2](https://user-images.githubusercontent.com/48377582/54068512-1c698500-4213-11e9-85be-66ab43a91825.png)

![TUnotil3](https://user-images.githubusercontent.com/48377582/54068610-86365e80-4214-11e9-8105-e394786a0c34.png)

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, this is not an airgeddon problem. This is a driver related problem. It seems the driver you are using is not using standard outputs... as you see on your last screenshot where it is supossed to be "Managed" it has "Access" which is a non-standard stuff.

Sorry but all I can say to you is to try another driver or maybe you could open an issue or contact to the driver developer in order to perform modifications to be in the standards. We are not going to develop customized stuff for only one driver, sorry. Closing.

**Comment by v1s1t0r1sh3r3** [comment]
I see in your screenshots you are using Kali Linux. Try using driver present in the package realtek-rtl88xxau-dkms which is available to install using apt. You can see similar issues opened here:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/100
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/185
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/225
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/203
