### ISSUE TITLE
Still not installing

### ISSUE THREAD

**Issue by MohammadBinAftab** [v1s1t0r1sh3r3/airgeddon#253]
Hey there.
 When I wrote apt install bettercap .
It gives a error.
That is unable to locate package .
Please give a full installation process.

**Comment by OscarAkaElvis** [comment]
Hi. You are wrong and this issue is going to be closed for many reasons.

In first place, you didn't followed the issue creation policy answering the needed questions to give you support. Now we are going to waste our time asking to you basic questions like what is your airgeddon version, what is your Operating System and that kind of things. As I imagine you know, the installation of packages is pretty different depending of the O.S. On Debian based Linux distributions it is done mainly by apt tool. On Arch based Linux is done mainly by pacman tool, yast tool for suse, rpm or yum for Red Hat based distros, etc etc. So we can't give to anybody a installation guide without knowing that data.

In second place, we are not here to give you support about how to install stuff on your Linux. This threads are to give support for airgeddon. Obviously you don't know Linux basics and you should try to learn that before trying to perform some hacking like using airgeddon tool.

In third place, your error description is pretty clear for us.... "it gives an error". Wow... pretty detailed! with that info the most probably thing is that anybody is going to be able to help you. For the next time try to describe with more detail what you did (commands used), the output (the error message) and what you are exactly trying to do. This is just and advice... not for this thread, for anywhere where you are going to ask for help in the future.

In fourth place, you already opened another similar issue (https://github.com/v1s1t0r1sh3r3/airgeddon/issues/252) ... we are going to start thinking that you are spamming us. Last warning. If you open a similar issue again you'll be blocked from this repo.

Closing and locking.
