### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by D1mar0n** [v1s1t0r1sh3r3/airgeddon#255]
Good day! Could you add to the script the ability to automatically install all dependencies and update them? Now I installed your script in Cali 2019.1 and it showed me during the installation that about 7 dependencies are missing. Now you need to spend a lot of time searching for their repositories and further installation. It would be very convenient to be able to do it all straight from the skipt menu. Thank you in advance for your response.

**Comment by v1s1t0r1sh3r3** [comment]
No sorry. airgeddon is compatible with multiple systems. Most used are debian based like Kali or Parrot, and dependencies can be installed using apt, but airgeddon is also compatible with a lot of systems. Some of them Arch based use pacman for package managing, others like Suse are using yast, Red hat based are using yum, etc.

Due this multiple possibilities and the complexity of doing compatible to all of them this part is not done.

Regarding your time spent looking for the repositories to find the right packages, that is because you didn't read correctly what airgeddon told to you once a dependency is missing. It is saying the possible package name. For example if you are missing the "dhcpd" command, it says the package can be "isc-dhcp-server" or "dhcp-server" or "dhcp". In the case of Kali/Parrot the right package is "isc-dhcp-server", so as simple as launch "apt install isc-dhcp-server. So you only need to launch apt trying the suggested names, all is done in less than two minutes.

**Comment by D1mar0n** [comment]
Thank you so much for the answer! This is very important when there is fast feedback from the developer. Now I will try to install everything that is not enough.

Another question: can you make the "fake network" also protected and not open? I mean something like this [Hostabe by Koala633](https://github.com/Koala633/hostbase/)

**Comment by v1s1t0r1sh3r3** [comment]
But if you create the fake network for Evil Twin with password, legitimate users are not going to be able to connect I think...

**Comment by D1mar0n** [comment]
Yes, you are probably right ... It Koala633 works differently. It's a pity. In any case, thanks for the reply and look forward to new versions. If you need to test something, I will always be happy to help. Good luck to you!

**Comment by DrPhilosophus** [comment]
@v1s1t0r1sh3r3 I couldn't get the following packages for Arch linux: mdk4, hostapd-wpe. I installed beef from a github repo and crunch from sourceforge as it's not available when I search edfor the possible package name. I did searched the web, but I couldn't find.

**Comment by OscarAkaElvis** [comment]
This is not too much related to airgeddon... anyway, I can recommend to you to use some pentesting-tools repo like ArchStrike: https://archstrike.org/

You have there all the needed tools including airgeddon itself. Good luck.
