### ISSUE TITLE
Evil twin internet leakage without logging to the captive portal

### ISSUE THREAD

**Issue by an0n5urf** [v1s1t0r1sh3r3/airgeddon#261]
Is there any way to forbid internet access or redirect to captive portal for the users connecting to the fake ap?I am using Parrot OS and airgeddon version 9.11 .I am using evil twin with internet interface as usb0(usb tethering) and a single wifi card for fake AP.The problem is that the victims are able to access internet without even logging to the captive portal, even though the captive portal is showing/popping at the time of logging to the AP?

P.S. : The AP is open.

**Comment by v1s1t0r1sh3r3** [comment]
If you are asking in general without using airgeddon I can't answer you. What I can say to you is that airgeddon has different Evil Twin AP modes. All of them except one are giving internet access to the victims because the point of that kind of attacks is to allow surfing for the victims while you are stealing to them credentials and that kind of stuff because of the MiTM (man in the middle) you have set with the fake access point.

If you are using the airgeddon's captive portal Evil Twin, the victims will not be able to surf. All their dns requests will be redirected to the captive portal acting as a "DNS blackhole". In fact, when you set up it, you have two available options, one of them is using dnsspoof and using that kind of scenario is not needed to have internet access working to launch the attack. So answering to your question, yes, it is possible using airgeddon. Please, next time read about the tool or try to use it before opening an issue. Closing.
