### ISSUE TITLE
WPS pixie attack doesn't work anymore

### ISSUE THREAD

**Issue by Dema323** [v1s1t0r1sh3r3/airgeddon#263]
So this morning i did a pixiedust attack on my ASUS router and i got the pin in like 2 seconds. Now i have been trying to reproduce this for the last 2 hours and pixiedust seems to be unable to get me the pin. When i got the pin i was further away then i am now and im doing exactly the same thing. I checked if the router locked wps but it didn't and i also rebooted the router a couple of times but no luck. If this is not the place to put this please let me know where i should ask this.
Thanks for your time.

**Comment by v1s1t0r1sh3r3** [comment]
In first place, if you want to be helped, you should fill completely the issue creation template in order to avoid now al the questions regarding you O.S., your airgeddon version, chipset, etc etc... 

If it worked for you once, it seems airgeddon configuration is ok. Pixie Dust attacks are already pretty tested and are working fine in airgeddon.

Anyway, airgeddon is a wrapper which use a lot of third party tools. Maybe you can ask to the developers of that tools (not sure yet if you used bully or reaver). Perform all kind of resets (not only AP, even your machine, try closer, etc). Sorry but we can't say more about this. We are not a wireless hacking helpdesk support. We are here just to talk about possible airgeddon issues and this seems it is not. Closing.

**Comment by Dema323** [comment]
Okay no problem. Im gonna keep posting my findings in here if that's okay. For other people and future reference. -- So i tried wpspin again from the exact spot i did when it worked. And i think it doesn't work when i am to close to the router wich is weird.
