### ISSUE TITLE
evil twin network doesn't get created

### ISSUE THREAD

**Issue by krimodzlou** [v1s1t0r1sh3r3/airgeddon#264]
#### Is your question related to any concrete technology?
i dont know what is concrete technology

the fake network doesn't get created
#### Describe your question as detailed as possible
whene i do the evil twin attack every think works good.
but in the end efter getting handshack and kicking users off from the network.
the indentical fake network doesn't get created.

**Comment by OscarAkaElvis** [comment]
This topic sounds more like an issue instead of a question. It seems you chosen the wrong template to fill. Please re-open an issue but this time with the right template and be sure that you fill up all the needed questions (airgeddon version, O.S., chipset of your card, etc). How do you pretend to be helped without details? be concrete, put screenshots, etc. Closing.
