### ISSUE TITLE
Can't install mdk4 to run airgeddon

### ISSUE THREAD

**Issue by hassanmonji** [v1s1t0r1sh3r3/airgeddon#269]
#### What is your airgeddon version?
v9.20
I used the one available on GetHub
https://github.com/v1s1t0r1sh3r3/airgeddon

#### What is your Linux O.S. and which version?

Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux

#### Which is the chipset of your wireless card?

Alfa AWUS036ACH

#### Describe the issue and the steps to reproduce it

i used the following steps:
git clone https://github.com/v1s1t0r1sh3r3/airgeddon
then
I tried to run the code ./airgeddon.sh
it shows that there are some missing tools such as:
bettercap
mdk4
lighttpd
dhcpd

i used apt-get install to fix the issue but the only one couldn't install is mdk4 here is the following:
![Capture](https://user-images.githubusercontent.com/48393624/59549237-4bef0280-8f63-11e9-87f4-70646930de99.JPG)

apt-get install mdk4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mdk4

**Comment by v1s1t0r1sh3r3** [comment]
What? mdk4 is on kali repos... Stupid question... did you performed `apt update` before `apt install mdk4` ??? if no, that's your problem.... if yes, you have some kind of problem with your configured kali repos. Check your /etc/apt/sources.list . Mine contains:

deb http://http.kali.org/kali kali-rolling main non-free contrib

Anyway, this problem is out of scope of airgeddon... is not an airgeddon issue. Closing.

**Comment by hassanmonji** [comment]
I will not get down to your level saying that your answer is stupid, but I will tell you that I performed all of the following:
before installing the airgeddon
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
reboot

then I installed  your stupid program

**Comment by v1s1t0r1sh3r3** [comment]
I answer with stupid answers to stupid questions.... pretty much n00bs asking here for a long time... maybe you could point on your question that you've already did that. If our program is stupid, why are you using it?

Anyway, we are not a helpdesk support. This is not related to an airgeddon issue. Closing, blocking and banning you.

**Comment by OscarAkaElvis** [comment]
It seems Kali removed mdk4 package from repos because it was removed from testing Debian repos: https://tracker.debian.org/news/1040944/mdk4-removed-from-testing/

I opened an issue (https://github.com/v1s1t0r1sh3r3/airgeddon/issues/271) to create an option for mdk3 retrocompatibility and @JBalanza will be in charge of doing it. I put this post as a reference. Locking again 😸
