### ISSUE TITLE
Can you point me to the code that triggers captive portal

### ISSUE THREAD

**Issue by usama7628674** [v1s1t0r1sh3r3/airgeddon#277]
@OscarAkaElvis Just a general question when a victim connects to fake AP android will trigger a captive portal automatically.I want you to point me to that code in script.

**Comment by OscarAkaElvis** [comment]
A simple search for "captive portal" on closed issues can give you the answer. https://github.com/v1s1t0r1sh3r3/airgeddon/issues/241

**Comment by usama7628674** [comment]
@OscarAkaElvis I'm talking about requests android send to make sure it is connected to internet for example
In case of android `connectivitycheck.gstatic.com/generate_204 `
For apple device `captive.apple.com`

There are other requests as well my question is where does airgeddon put these requests in which directory or code?

**Comment by OscarAkaElvis** [comment]
In first place, to create an issue you need to follow the issue creation policy. Please, next time be sure to fill out all the needed questions in order to save time to all and try to be clear on the first post. If you need to clarify it in a second post is clearly because your post is not well done. Time is gold.

airgeddon doesn't need to set the urls that you are talking about because they are changing on each android version... to maintain a list could be crazy. It is automatically detected by devices because of the "DNS blackhole". All requests are redirected to the captive portal by dns and that is detected by the devices.

**Comment by usama7628674** [comment]
@OscarAkaElvis The dns server which airgeddon uses is dnsmasq.Is this right?

**Comment by OscarAkaElvis** [comment]
No, it is not. The command used is `dnsspoof` which is part of the dsniff package.
