### ISSUE TITLE
No changing Pins Pixie Dust Attack

### ISSUE THREAD

**Issue by lebohnes** [v1s1t0r1sh3r3/airgeddon#286]
![Screenshot from 2019-08-14 12-49-30](https://user-images.githubusercontent.com/54107044/63022291-19458580-be92-11e9-9b50-88bd6a8e379c.png)
What is your airgeddon version?
9.21

What is your Linux O.S. and which version?
Kali Linux Rolling Release 2019.3 for Raspberry Pi 4b

Which is the chipset of your wireless card?
Qualcomm Atheros Communications AR9271 802.11n

Steps:
1. Changed to monitor mode
2. Explored and choosed target
3. (bully) pixie dust attack

=> While the attack only one pin was used. The Pins does not changed. 

Greets

**Comment by OscarAkaElvis** [comment]
This is completely normal because if it is not able to connect to the AP, it's not going to change the PIN to try another one... the problem is not the PIN. The problem could be a lot of different things. Not all WPS APs are vulnerable to Pixie Dust, in fact, only a few one are vulnerable. This is a completely normal behavior using bully when your target is not vulnerable. It could be a lot of factors, low signal, PBC (Push Button Connect) enabled, etc...

Pixie Dust attacks are working since a lot of versions in airgeddon and the code wasn't changed since a lot of time. The most probably problem here is not airgeddon. Closing.
