### ISSUE TITLE
Can't see password

### ISSUE THREAD

**Issue by stridjj** [v1s1t0r1sh3r3/airgeddon#289]
#### Is your question related to any concrete technology?
Android 7.1.2 Kali Nethunter
 (cat /etc/*-release)
   DISTRIB_ID=kali
   DISTRIB_RELEASE=kali-rolling
   DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
   VERSION=2019.1
   VERSION_ID=2019.1
   ID_LIKE= debian

(uname -a) 
Linux Kali 3.18.35-beacon_second_bake # 1 SMP PREEMPT 2018 aarch64 GNU/Linux

USB wireless adapter "blueway" with RT3070 chip

#### Describe your question as detailed as possible
Can't see password which target entered . The following steps were done:

Started Evil Twin attack from my android phone with kali nethunter and AP works fine. (here is screenshot examples)
![ScreenshotLeft01](https://user-images.githubusercontent.com/48788888/63160469-812cd500-c026-11e9-9a43-7be1fa7b2eae.png)
![ScreenshotRight02](https://user-images.githubusercontent.com/48788888/63160647-ef719780-c026-11e9-9c93-c94177ceeae9.png)

And then I use target windows 10 machine. You can see that page is loaded properly: 

![CaptivePortal01](https://user-images.githubusercontent.com/48788888/63160738-2f387f00-c027-11e9-9943-0d1c3f350b17.png)

But when I entered INCORRECT password I unable to see target's attempts and appears error at "webserver" window
![ScreenshotRight03](https://user-images.githubusercontent.com/48788888/63160997-bf76c400-c027-11e9-801b-4a1aa6cb711e.png)

The same occurs when I input CORRECT password
![ScreenshotRight04CorrectPass](https://user-images.githubusercontent.com/48788888/63161128-01076f00-c028-11e9-9246-b997cee65cf3.png)

But on target machine appears following page:
![CaptivePortal02](https://user-images.githubusercontent.com/48788888/63161151-0a90d700-c028-11e9-9bda-65788b6e590c.png)

Could you explain why does this occur and how can I fix it?

I do not know what other information would be useful for you, so
please tell me if you need some other information
Thank you.

**Comment by OscarAkaElvis** [comment]
Hmmm.... pretty weird, it usually works like a charm. Probably it's related to launch this in Kali Nethunter from a phone. Watching your screenshots, seems that it could be related to how to process the POST request. I checked the related piece of code in airgeddon.sh

![image](https://user-images.githubusercontent.com/5803348/63163414-99e8bb00-c025-11e9-98ef-25737fee3eb9.png)

It seems in your device, for some reason, `/dev/stdin` is not available... pretty weird because is something that all Linux should have by default.

I launched captive portal using a virtual Kali inside my Android and it worked fine. I used Linux Deploy app to run Linux. I can't try Kali Nethunter due an incompatibility with my device so I can't really tell you how to handle this but I can say that the reason is probably fault of Kali Nethunter which is not fitting the mininum Linux standards due the lack of `/dev/stdin`. Not sure now if there is a more compatible way to do this.

**Comment by v1s1t0r1sh3r3** [comment]
Kali Nethunter is not supported by airgeddon. Closing.

Anyway, feel free to write on this thread if somebody find a fix or a workaround for this. It could be useful for somebody.

**Comment by stridjj** [comment]
Kali Nethunter is supported by airgeddon! You will laugh...
To make it work one need another Linux computer. Just copy /dev/stdin and /dev/stdout files from PC and past it in / dev on you android kali nethunter, that's all. Airgeddon then will work properly but after a phone was rebooted need to copy and past these files again.

**Comment by stridjj** [comment]
OscarAkaElvis, you told that you launched airgeddon from phone just using WM. Did you use external wifi card? And if you did it seems you changed kernel of your phone to another which supports external wifi cards. Is it so?

**Comment by OscarAkaElvis** [comment]
Really? does that copy/paste trick work? wow... dirty workaround! but if it works... I'm glad to hear that!

Yeah, regarding to use Kali using Linux Deploy app, I'm using a custom kernel called "coconut kernel" for my OnePlus 3, which is the best kernel you can have for that model. It has support for some usb wireless cards (you'll need an OTG usb cable) and many features. It's really nice. A link to it: 
https://forum.xda-developers.com/oneplus-3/development/kernel-coconut-kernel-oos-oreo5-x-x-t3902040

The main author of the kernel is mainly @xpz3 , is one of the airgeddon collaborators. Cheers.

**Comment by stridjj** [comment]
no, copy/ past didn't work actualy. I edited the comment with another solution

**Comment by v1s1t0r1sh3r3** [comment]
> Kali Nethunter IS SUPPORTED by airgeddon. I found the solution

I just say that is not officially supported by us. You should say "it's working". Good for you if it works with that workaround.
