### ISSUE TITLE
Error with the detection of the card

### ISSUE THREAD

**Issue by Robotakademie** [v1s1t0r1sh3r3/airgeddon#291]
#### What is your airgeddon version?

Airgeddon Version 9.20

#### What is your Linux O.S. and which version?

Latest Parrot OS

#### Which is the chipset of your wireless card?

I have the TP Link Archer T4UH with the realtek rtl8812au chipset

#### Describe the issue and the steps to reproduce it

First of all, airgeddon doesn't detect the chipset. Everything works fine with airmon and everything looks fine in iwconfig. When I select the Interface in airgeddon and set it to Monitor Mode, it says that it's renamed to enabled and does not support wifi. When I try to select it (still named wlan1) in the menu the script says that an error occurred when selecting the network and the script stops. Please help.

**Comment by Robotakademie** [comment]
Note: The drivers are all properly installed

**Comment by OscarAkaElvis** [comment]
First, try to use latest version of airgeddon (v9.21 at this moment) instead of 9.20. It seems parrot staff didn't deployed yet on their repos.

Second, regarding your "note: the drivers are all properly installed". Which drivers? That card is always the same song: problems problems problems... if you search through closed issues you'll see that a lot of times the people are having problems with that chipset. Some people are using drivers from aircrack repo, some people are using custom drivers and I saw that some people solved their problems using the "realtek-rtl88xxau-dkms" package that can be installed by apt. To be honest, I don't have that problematic chipset on my own to do tests, so all I can say is: "try another one! that chipset is causing a lot of problems".

Third, can you give some data? you said chipset is not detected... that is weird... other people who had problems with that chipset at least had it well detected. So I guess apart of the chipset, maybe your card could be even more special or rare. airgeddon is detecting the chipset based on some "proc" stuff. Could you give the output of these commands? Let's suppose your card is named wlan0.

`cut -f 1 -d ":" < "/sys/class/net/wlan0/device/modalias"` -> this should show "usb" if your card is plugged by usb, is this an usb card?

`cut -b 6-14 < "/sys/class/net/wlan0/device/modalias" | sed 's/^.//;s/p/:/' ` -> this should show something like this: `CF3:9271`, this is the result of my Alfa Atheros AR9271 card. This result will be used on next command.

`lsusb | grep -i "CF3:9271" | head -n 1 | cut -f 3 -d ":" | sed -e "s/^[0-9a-f]\{1,4\} \|^ //Ig;s/ Network Connection.*//Ig;s/ Wireless.*//Ig;s/ PCI Express.*//Ig;s/ \(Gigabit\|Fast\) Ethernet.*//Ig;s/ \[.*//;s/ (.*//"` -> you should replace `CF3:9271` by the result of the last command.

What are these commands giving to you as output? All of this is in the set_chipset function. Maybe your card is different and this function could be improved. We are open to receive Pull Requests. Thanks.

**Comment by Robotakademie** [comment]
When I have said, that the drivers are properly installed, i mean the driver realtek-rtl88xxau-dkms from apt.
The result from "cut -f 1 -d ":" < "/sys/class/net/wlan1/device/modalias"" is usb.

The result of the other command is 357:0103
 and the last command didn't give any result.
![image](https://user-images.githubusercontent.com/33637021/63406564-99b43b00-c3ea-11e9-9a0f-ca145324143f.png)
It still doesn't detect the chipset. This is a screenshot.
When I try to put it in monitor mode, this happens: It says it is renamed enabled and is no wifi card.
![image](https://user-images.githubusercontent.com/33637021/63406779-22cb7200-c3eb-11e9-9c51-3fb1b6981fa6.png)

**Comment by Robotakademie** [comment]
Note: My interface is wlan1 and when I put it to monitor mode it doesn't change name

**Comment by OscarAkaElvis** [comment]
I see you have another card. Is airgeddon working for you on your other card?

Yeah, the no change of the name is normal. That is because that card is not fully compatible to airmon. Some update in airmon tried to be compatible with more cards but as you can see, it is not fully working. This is not caused by airgeddon. You can check it completely out of airgeddon. Just open a console, plug your card, launch `airmon-ng start wlan1` and check the new name of the card. Is it called wlan1mon as usual? I guess no. That is because the behavior of airmon regarding that card is not fully working, what can I say... if is not fully working by aircrack suite it will be not fully working with airgeddon. Just use another card.

Regarding the chipset detection, is quite hard without having that model to add a rule for it... anyway we can try. What is the output of this command? `lsusb | grep -i "357:0103"` . Maybe with all the raw output I could modify the sed command in order to at least detect the chipset.

**Comment by Robotakademie** [comment]
The command gave some weird errors and besides that, as it is not fully compatible to airmon, i consider bying a new adapter. Inq the Internet I found the Alfa AWUS036NHA. Would changing to this adapter stop the problems? It it compatible?

**Comment by OscarAkaElvis** [comment]
Sure man, tha Alfa card is nice. It has an atheros AR9271 chipset which is fully compatible to airmon and also to airgeddon. The "problem" of that card is that is not 5ghz, is just 2.4ghz but it works like a charm, I have one of them.

Regarding the command... errors? just launch this: `lsusb | grep -i "357:0103"`. If you are getting errors just launch `lsusb` and put here the entire output please, just to figure out how to get the chipset from your card. Thanks.

**Comment by Robotakademie** [comment]
Something funny Happend.. I pluged it in to try the command when the device suddenly died. I could'n geht it running so I used my warranty in It. So ... Now I'm going to buy another but I didn't KNOW for sure which one is the best in a budget of 35€. Does someone have any Suggestionen? PS: My Personal favourite is The Alfa AWUS036NHA. Ist this good or shall Ibuy another?

**Comment by OscarAkaElvis** [comment]
I can tell you that on 5ghz I have fully working airmon compatible and airgeddon compatible Alfa AWUS052NHS with RT3572 chipset. It works like a charm but is a card hard to find! out of existences. Good luck!

**Comment by Robotakademie** [comment]
Thanks. I'm gonna Look if I can find It. If Not, I'm gonna buy The Alfa AWUS036NHA

**Comment by OscarAkaElvis** [comment]
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer
