### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by Danysevian** [v1s1t0r1sh3r3/airgeddon#299]
How can you read the letters in Arabic? Because the name of the network being special characters when I try to use Evil-Twin works but the name of the network comes out with many rare symbols and does not put the real name of the network to perform the attack. Could you help me? Thank you

**Comment by OscarAkaElvis** [comment]
Hi, somebody in the past told me about to translate airgeddon into some arabic language. The problem here is that bash is not supporting RTL (Right To Left) languages.

Regarding to special chars on a network ESSID, I guess is the same as Russian, Chinese or other languages with specific symbols. To be honest, I didn't tried the tool over networks with special chars from other languages because where I live (Spain) we have only some of them (like `ñ` for example), and it is working fine just configuring my Linux to use UTF-8. I think that if you configure your lang of your Linux to use UTF-8 that should be enough. Closing.
