### ISSUE TITLE
total beginner question 

### ISSUE THREAD

**Issue by ahmedbenammar029** [v1s1t0r1sh3r3/airgeddon#301]
#### Is your question related to any concrete technology?
no

#### Describe your question as detailed as possible

hey great tool, I'm currently learning how to code and I just want better internet so I have no time to learn about networks right now, so as far as I know, I need to install Linux OS and a network adapter, right ??

**Comment by OscarAkaElvis** [comment]
Not sure to understand your question.... you "want better internet" ??? If you mean you want to hack some neighbour to use his/her internet, what I say to you is that is illegal. This is a tool to be used on authorized pentests or to test with your own network just for learning. Closing this because not sure what are you talking about.
