### ISSUE TITLE
Interface 'enabled' selected. Mode: (Non wifi card)

### ISSUE THREAD

**Issue by jdhau** [v1s1t0r1sh3r3/airgeddon#304]
####  What is your airgeddon version?

v9.22

#### What is your Linux O.S. and which version?

Kali 2019.3

#### Which is the chipset of your wireless card?

rt8812au, driver https://github.com/kimocoder/rtl8812au (fully airmon compatible)

#### Describe the issue and the steps to reproduce it

First of all, I'm aware this chipset has issues, but with this latest driver I've got it to work perfectly with airmon, and this issue seems like a bug in the Airgeddon script rather than a driver / chipset issue. For some reason when I choose to set my adapter into monitor mode, Airgeddon will inform me that interface has changed its name (airmon doesn't actually do this for me) and autoselect this new interface. 

Monitor mode is enabled successfully, but what the script does afterwards, is select a non-existing interface called 'enabled'. I figure this is probably a bug in how the output of iw / airmon commands is parsed?

![image](https://user-images.githubusercontent.com/37823848/65161626-3e25ad80-da7b-11e9-87c2-8faf2a735ed5.png)

![image](https://user-images.githubusercontent.com/37823848/65161661-509fe700-da7b-11e9-8539-3ab0324a99a7.png)

**Comment by OscarAkaElvis** [comment]
The problem here is because the driver is not working as normal drivers usually are doing. The parsing is the same for all. If this is failing with this driver is not because an airgeddon issue. Is because the driver is not giving back the required output in the right place.

Maybe we could do some tests, checking closely the output etc etc but it doesn't worth the time for us because we are not going to modify anything to fit special stuff for a concrete chipset. It was said a lot of times before on these issue threads, that we don't really like to do modifications for specific chipsets due specific stuff developed in that driver.

I don't want to spoil too much, but probably in the future it could be easily fixed using the new plugin system which is under development... more info about this soon 😄

**Comment by Norup123** [comment]
I am having this exact issue. Did you ever find an actual fix/workaround for it?

**Comment by jdhau** [comment]
I’m afraid not. Turns out the rt8812au does not support virtual interfaces
(it’s not a mac8022 driver) and as such cannot be used for evil twin
attacks on its own.

**Comment by OscarAkaElvis** [comment]
Yeah, you can see it here: https://github.com/aircrack-ng/rtl8812au/issues/417

Not sure if @kimocoder or any other driver developer can do that. Until that, all that can I say is to check the card & chipsets compatibility list from our Wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Anyway, not sure if at this point some driver worked (not the aircrack github repo) at some point. I don't own a card with that chipset, hard to say for me... but If I don't remember bad, I've heard that the version from the apt repos `apt install realtek-rtl88xxau-dkms` worked time ago.... can't tell this 100%

**Comment by Norup123** [comment]
Meaning i bought a useless adapter? The prepurchase research i did said it was able to go in to monitor mode, and packet injection, but i guess this in it self is not enough to test these attacks? =/

**Comment by Norup123** [comment]
I actually cant find anywhere to buy any of the ones on the list. They seem terribly outdated

**Comment by OscarAkaElvis** [comment]
Are you kidding me? My first search in google using "rt3070 wifi" shown a lot of amazon, ebay and other links. There are TONS of adapters using that chipsets.

**Comment by OscarAkaElvis** [comment]
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer

**Comment by jdhau** [comment]
OMG you fixed the 8812? How? I thought it was incapable of mixed interface
modes?

**Comment by v1s1t0r1sh3r3** [comment]
From airgeddon v10.0 there is a plugins system available. With that plugin the interface mode switching is fixed. Now you can switch from managed to monitor and viceversa flawlessly from airgeddon and you can create Evil Twin APs. The plugin is parsing outputs in a special way to fit the uncommon output of these cards.

The are still some problems related to perform DoS while at the same time the Evil Twin AP is created and problems also related to use WPS but all of them are related to the driver. The plugin fix all possible stuff that airgeddon can do. I mean that that at least now you can use the card in airgeddon for standard operations (scan, mode switching, etc). Enjoy!

**Comment by fraznistpunk** [comment]
i am using Kali linux as secondary os on my laptop and when i cloned Airgeddon repo previously, my wireless card was supported for airgeddon but after recent update it shows that "The wireless card you selected is not supported".
My wireless card info: RTL8821AE 802.11ac PCIe Wireless Network Adapter
Please help me through!!

**Comment by OscarAkaElvis** [comment]
You said "after recent update"... i guess you are referring to Kali update... not to airgeddon update, because in airgeddon there is no changes about this. Probably on the kali update the kernel was upgraded or the driver (or both), and that can be causing the mess. Join to the Discord channel to see if somebody can help you to discuss further. You can find the invitation link on contact 
section at wiki.

**Comment by afiadi-s** [comment]
Airgeddon V10.40 is suck much better fluion, My USB Wifi card Bus 002 Device 002: ID 2357:0108 TP-Link TL-WN822N Version 4 RTL8192EU
cannot use in monitor mode, even though my usb card is work flawlessly in monitor mode, injection mode and master mode in fluxion and airmon-ng. I don't know how to solved it, maybe is bug from Airgeddon because airgeddon also use software tool aircrack-ng suite and my usb wifi card works flawlessly in aircrack-ng suite, but failed to enable monitor mode in airgeddon v10.40

**Comment by fraznistpunk** [comment]
There is again some issue ,please help, after capturing handshake file from a target, when I select language for Evil Twin Attack Captive Portal, it exits with error Interface changed its name while set to managed mode.

**Comment by OscarAkaElvis** [comment]
Probably something on your card is messing it up. Join discord channel to discuss further. Inviation link: https://discord.gg/sQ9dgt9
