### ISSUE TITLE
Evil Twin with Captive Portal + Whitelist & Internet

### ISSUE THREAD

**Issue by RasyiidWho** [v1s1t0r1sh3r3/airgeddon#314]
First, I'm not good at english. So, I hope everyone understand what I mean..

#### Describe the feature or compatibility enhancement and involved versions if apply

Modern android (I use MIUI as example) has checker squence to detect if the wifi has internet access or not with accessing some url. And whenever it's doesn't have internet access, MIUI block all traffic (including dns blackhole) so client can't access our captive portal. Is this possible to make capacitive portal with whitelist + internet? so internet checker url (in whitelist.txt) will detect that our fake AP has internet access (using internet interface), but other than in that whitelist, it's redirect to captive portal.

#### What are the benefits of adding this?

In current evil twin with captive portal, alot client can't access any links when android detect that ap doesn't have internet, I hope this feature can fix that.

**Comment by xpz3** [comment]
This will be fixed in next release. We already have the solution for that. Currently we are working on plugins integration in airgeddon after which a captive portal fix will be added too.
You can join our discord channel for more discussion if needed. If you want to do some tests with your phone, join discord and mention there that you are ready to do.

**Comment by OscarAkaElvis** [comment]
This is at least done! Thanks to @xpz3 . It will be released as expected on the next v10.0. Closing this.
