### ISSUE TITLE
not installing optional dependencies 

### ISSUE THREAD

**Issue by saintofinternet** [v1s1t0r1sh3r3/airgeddon#327]
#### What is your airgeddon version?

Script V10.0

#### What is your Linux O.S. and which version?

Kali Linux

#### Describe the issue and the steps to reproduce it

Gives the following Error  when trying to install dependencies
An error occurred while trying to install dependencies. This may be due to multiple causes. Make sure your internet connection is working. Anyway, you have installed all essential tools so you can continue. You'll miss only some features

**Comment by OscarAkaElvis** [comment]
Yeah, that is because the "missing_dependencies.sh" plugin is trying to install the packages you are missing. This plugin is applying only for some O.S. and Kali is one of them, so it tries to perform first an `apt update` command and then an `apt -y install whatever` . It depends on what you are missing.

Thousands of things can go wrong here. Impossible to know without more info!

Maybe your internet connection is not ok. Or maybe you are not resolvig well the Kali repo dns, or maybe Kali repos are temporary down... etc. Who knows! but I can tell you that it usually works well.

Maybe you could try to do the installations manually using apt command. Probably you'll get the same results but at least will be able to see the errors.

**Comment by darknodi** [comment]
@OscarAkaElvis Hi. 

from the bash script command. 
can I take credential logins from someone that is logged from wireless router. 

example. 

1.connected 

instagram.com:80
example@mail.com
passwords20000

stop the command CTR-C
to stop spying command from wireless router.  @OscarAkaElvis

**Comment by OscarAkaElvis** [comment]
First of all, it semms what you are talking about is not related to the open issue. Second, I don't understand exactly what you are talking about.... join the Discord channel to discuss deeper.

Anyway, I'm going to close this issue due inactivity.
