### ISSUE TITLE
WPA Handshake cap

### ISSUE THREAD

**Issue by hackvice** [v1s1t0r1sh3r3/airgeddon#328]
#### Is your question related to any concrete technology?

Linux

#### Describe your question as detailed as possible

Hi, I would like to ask about the handshake cap files.
I have useful capture the handshake but my file was exported to txt and named enterprise capture. My question is whan kind of hash Type is used for that capture? There are 2 files named over hashcat and john. I tried to insert the hashes in either of those tools but it's not recognized by them. Thanks! 
Here is the hash btw - ::::ba9b1d093842a4861b94c8e35486706e74917b7d717cb0b4:dcffc9555babdb21

**Comment by OscarAkaElvis** [comment]
You are misunderstanding how it works. I think you are working on enterprise network and not on personal network. The handshake capture is only for personal network and it is saved as a .cap file to be decrypted offline later but in your case, you are working on enterprise networks, so no handshake is captured for you. Forget about handshake.

What you have, are two different txt files containing the hashes of legit clients and now you can try to decrypt them offline in a similar way. airgeddon provides to you the way to do it using hashcat, john or asleap. You should choos the offline decryption menu for enterprise decryption. I can tell that they are well recognised. You are only missing the right way to do because you are treating them as handshakes wrongly.

Closing.
