### ISSUE TITLE
stucked in the evil twin step

### ISSUE THREAD

**Issue by ggrswiss** [v1s1t0r1sh3r3/airgeddon#332]
Hello everybody,

I'm running Airgeddon on the last Kali Linux
I have installed all the dependencies even those which are optional
Everything is OK at this point !
I have plugged my wifi card which is a ALFA AWUS036H and put it on the monitor mode while Airgeddon asked for it.
I have managed to get the Handshake ... save it in a file etc... and everything is running pretty good ! but when i want to go to the next level: "creating the fake AP" it doesn't work !
what does that mean ? actually, the target doesn't receive any logging page, ito sum it up: Nothing happen.
and furthermore the target doesn't have the access to log back to the AP, internet doesn't work but i can't see an other twin AP as it is explained in many tutorials.
(the mutliples opened windows are stucked and we can do nothing)
I tried to change the target: one time, it was a PC running Windows 7 and as it didn't work i tried to choose as a target a phone which runs android ... but it doesn't work too ...

Could you tell me what should i do ?
 
Thank you for your help,

**Comment by OscarAkaElvis** [comment]
In first place, you didn't filled the issue template so I'll close it.

Anyway, I can tell you some things... first, your Card is one of the blacklisted cards. You can check this: 
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

If you are using airgeddon v10.0 (we don't know because you didn't filled the template), you can work with that card and airgeddon using the known plugin I did for compatibility with that awful cards: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer

Anyway, you'll have a problem for Evil Twin that we can't solve... if you read carefully the readme file on the plugin link I pasted to you, you'll see that the plugin is fixing the problems that are in airgeddons side. But the driver still have some problems. One of them is while creating the Evil Twin attack, the DoS part is not working due a driver problem but in any case you should be able to see the fake ap, connect to it and see the captive portal.

Good luck. Closing.

**Comment by ggrswiss** [comment]
Thank you for your respond,
I have checked the list of wifi cards and mine doesn't appear in the blacklist.
I have the ALFA AWUS036**H** NOT the AWUS036A**CH** which is the new one  (black with two antenas which works on 2Ghz and 5Ghz) Mine is the old one, then i don't understand what to do ?!
What could be the problem as my card is supposed to work fully with airegeddon and airmon ?

**Comment by OscarAkaElvis** [comment]
Oooops, I thought that it was the AWUS036ACH. Weird... your Alfa card AWUS036H has a Realtek RTL8187L chipset... it should work. Can you check it? just a simple `lsusb` command or a screenshot on the interface selection menu on airgeddon should be enough to get the chipset.

Did you tried to launch manually this command just before launching airgeddon? `airmon-ng check kill`. Just wondering... is hard without providing versions, operating system, etc.

**Comment by ggrswiss** [comment]
Yes, it's a RTL8187 chipset
I tried to lauch the kill command as you told me but it still doesn't work.
I'm wondering if during the process of "The Evil Twin AP" 
Do i have the necessity to have internet during this step or not ? maybe that's why it crashed ... well i don't know ... i will try to make some captures of my screen and send it here to show you step by step what's happened. In any case, the target is my PC running windows 7 pro 64bits
- firefox updated etc...with Adblock plus 
if the AP twin appears like a pop-up page it could be deleted automatically (i just suppose it, as i have never seen anything on the windows desktop
- Kaspersky Antivirus

I'm running the attack from my laptop with Kali linux on an external SSD (not a live but installed on the drive)

Leave me some minutes to send you the pictures ... i'm coming back !

**Comment by OscarAkaElvis** [comment]
Weird. Captive portal does not need internet access. For all the attacks which need internet access, airgeddon is performing a validation in order to determine if the attack is possible or not. Is not the case of the captive portal attack.

Please, to keep trying to help you better do it on Discord channel. Join to it, the link is on contact section of our wiki. Cheers!

**Comment by ggrswiss** [comment]
OK ! i have posted a message on Discord channel with some screenshots
I hope you understand french :-)
