### ISSUE TITLE
Deauth Not Working 

### ISSUE THREAD

**Issue by AlienWolfX** [v1s1t0r1sh3r3/airgeddon#339]
#### What is your airgeddon version?

v10.1 

#### What is your Linux O.S. and which version?

Kali Linux 2020.1 

#### Which is the chipset of your wireless card?

Intel Corporation Dual Band Wireles(Internal Card)

#### Describe the issue and the steps to reproduce it

During the deauth on getting the handshake all works great but in the final part when a fake ap is created deauth doesnt work and displays an error about "No BSSID available" and also i think this is because of the network manager being disabled during this process, how do i fix this?

**Comment by OscarAkaElvis** [comment]
Yeah, that is a common problem for some wireless cards. For sure an Intel card is not the best choice to try to perform this kind of actions. Get a real good card and try again. You have a list of fully working cards here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Your problem is related to the ability to perform what is called multi-vif or "multiple interfaces". During an Evil Twin attack, airgeddon split your physical card into two logical cards. One is set in master mode to create the fake AP and the other one is set into monitor mode to perform the DoS attack. This can be done because both logical interfaces are working on the same channel due the physical limitation of "one card = one antenna = one channel at a time".

Intel integrated cards are not good to perform this kind of tasks. Anyway, if you want to share more stuff or still have some doubts, you can join our Discord channel where we can keep discussing anything. Here is the invitation link: https://discord.gg/sQ9dgt9

Closing.

**Comment by hushbiz** [comment]
I have a problem when im trying to deauth after capturing 4way handshake. Error message and disabel my adapter from monitor to managed.  Nothing happens

**Comment by OscarAkaElvis** [comment]
It could be for many reasons. Impossible to us without more data. OS? Card? Chipset? tests out of airgeddon using airmon? Please join Discord channel for further tests and questions.

**Comment by VishwasT** [comment]
The Deauth window is just checking for the channel 1, but my Target is on channel 3. What to do????

**Comment by OscarAkaElvis** [comment]
Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

And this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-dos-pursuit-mode-exactly

**Comment by rawnge** [comment]
How to change interface in deauth window to wlan0 from mon0?

**Comment by OscarAkaElvis** [comment]
You don't change interfaces in deauth window. You change it during the mode switch process in the previous menu.

Please, don't ask questions in other issues. If you want to ask questions, the best choice is to join to our Discord channel: https://discord.gg/sQ9dgt9

**Comment by pratitibanerjee** [comment]
While i am performing evil twin attack with captive portal , deauth is not occuring my target network device but the fake access point is being created successfully , though in window it's showing deauth requests are going on. but target devices on target network have internet connection

**Comment by OscarAkaElvis** [comment]
please, read the link given. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do
