### ISSUE TITLE
Capture PMKID in pcap or pcapng

### ISSUE THREAD

**Issue by Mike-Reddick** [v1s1t0r1sh3r3/airgeddon#345]
Please add an feature to capture PMKID in pcap or pcapng format, because some users use john the ripper to crack, so, with PMKID in pcap or pcapng, you can convert PMKID with wpapcap2john, wpapcap2john don't support .16800 as input, but support pcap or pcapng.

thanks

**Comment by JBalanza** [comment]
First of all, this Issue does not follow our Issue creation policy so we have to close it. Anyway and regarding to your question, we're actually developing PMKID capture and cracking. Stay tuned in order to get the last version of airgeddon when we release the feature. If you want further information, join our discord channel: https://discordapp.com/invite/sQ9dgt9

**Comment by OscarAkaElvis** [comment]
This feature was finally developed. Released onv10.10
