### ISSUE TITLE
Fast starting, with a Flag to check for tools only the first time.

### ISSUE THREAD

**Issue by R4z0rX** [v1s1t0r1sh3r3/airgeddon#348]
Hi!
It'd be awesome if the script can set a Flag in a local file that the initial check for tools has been made in this system with this version, so the next time the script will load faster.
And when the script is updated with a new version (probably needing a new tool), the script will check for tools again, and then set the Flag again for this new version.

Thanks for this awesome tool. :)

**Comment by OscarAkaElvis** [comment]
It seems you didn't explore too much the available options. What you want it is already done. Check this section of wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

Try to set to true the AIRGEDDON_SILENT_CHECKS option. Checks are done instantly and in a silent way.

**Comment by R4z0rX** [comment]
Oh, sorry! I missed that! It'd be nice to show that info at the script starting, with a short msg, like a tip, it'd be easier to know about that option.
Anyway, that's not exactly what I'm asking for. That make the checks anyway.
But now I see there's something better, AIRGEDDON_DEVELOPMENT_MODE skip all initial check. That's what I looking for! Sadly, it also skips the nicely done intro. :/
Thank you! :)

**Comment by OscarAkaElvis** [comment]
The checks must be done ALWAYS to keep the program coherence. But with that option enabled are donde instantly (all in less than a half second)... so don't worry. They take time when shown due the printing but it is intentional. Yeah, you can bypass the checks using development mode... but it makes no sense for you I think. Anyway is up to you. You have also another option to skip the intro... read all the available options.

**Comment by R4z0rX** [comment]
Oh, well, if the silent checks are so fast, then I could try that first.
Anyway, I still think there's no point to check everytime, if my system is static, never change, all the tools are there and will be there.
But, as I said in my request, it would necesary to re-check if the script updates ('cause, it could need a new tool).
Oh, and also, I've been programming in bash and lots of languages for more than 30 years. So, a Development Mode is cool for me. :)
And I'd love to contribute to cool projects like this one, but sadly I don't have enough time... :/
Well, anyway, I'll try your suggestion.
Thanks again.
Saludos! :)

**Comment by v1s1t0r1sh3r3** [comment]
It seems you don't understand that the checks are neccesary because you are not the person answering issues on github from users. Maybe your system is static, but the systems of thousands of users are not static. Maybe a user could uninstall a package without updating airgeddon... in that case it will fail if there is no check and the tool is not available... We (the team) are pretty tired of users complaining about issues that are not real issues.... we don't need more. We prefer to keep airgeddon as a robust tool checking as much as possible to avoid false error from users.

**Comment by R4z0rX** [comment]
Don't worry, I know it is exactly like that, and I absolutely agree with you.

**Comment by duraki** [comment]
Make this issue/fix more visible, like on actual README. Do end-users really have to look through the issue board to find this fix?

**Comment by OscarAkaElvis** [comment]
What fix? is not a fix, is an option that you can enable to perform the checks in silent mode. In any case, yeah... users usually don't read Wiki.
