### ISSUE TITLE
Interface changed its name while setting in managed mode

### ISSUE THREAD

**Issue by arykiller** [v1s1t0r1sh3r3/airgeddon#353]
#### What is your airgeddon version?

Airgeddon Version 10.10

#### What is your Linux O.S. and which version?

Kali Linux 2019.4 
Installed on VBox 

#### Which is the chipset of your wireless card?

wireless card: ALFA AWUS036NH
Driver: rtl8187
Chipset: Realtek semiconductor Corp. RTL8187

#### Describe the issue and the steps to reproduce it
First i select the interface to work with : wlan0
put it in monitor mode "2" and now the interface name is : wlan0mon
on the evil attack menu "7" i choose   "Evil Twin AP attack with captive portal " "9" 
i had no problem finding a target and getting the handshake 
right after choosing the language it shows "The inter face changed its name while setting in manged mode. Autoselected"
![kali linux  Running  - Oracle VM VirtualBox 3_19_2020 6_39_40 PM](https://user-images.githubusercontent.com/36006767/77085371-4dc58500-6a11-11ea-827f-97088738e7ab.png)

and hostapd shows 
![kali linux  Running  - Oracle VM VirtualBox 3_19_2020 6_46_15 PM](https://user-images.githubusercontent.com/36006767/77085851-f673e480-6a11-11ea-99f9-df64f8933f26.png)

**Comment by OscarAkaElvis** [comment]
Yeah, I can see that your hostapd screen (top left in green) is not ok... so you can't see the fake AP. You should see on that screen AP-ENABLED.

Try to launch the command `airmon-ng check kill` before launching airgeddon. 

Anyway I must say that you have one of the problematic chipsets. That chipset is known that has some problems... maybe is related to driver or maybe not... hard to say. I leave here a link with a list of the well working known cards. As you can see, your card is in the blacklist.

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Anyway, feel free to joing to our Discord channel in order to keep the support to try to help you. Invitation link is on Wiki on contact section: https://discord.gg/sQ9dgt9

**Comment by arykiller** [comment]
I tried to launch the command airmon-ng check kill before launching airgeddon 
and tried a different wireless card MediaTek with Chipset MT7601U and got the same issue 
i'll try the live version of kali and try airgeddon on my computer wireless card 
is there any wireless card you recommend that 100% work with airgeddon ?

**Comment by arykiller** [comment]
![Uploading 77194501...]()
It’s work just fine on the internal wireless card on live kali so i think its just the wireless chipsets 🤗

**Comment by OscarAkaElvis** [comment]
Yeah, please read the link i pasted here with the list of 100% compatible cards. Closing.

**Comment by curseblood123** [comment]
![image](https://user-images.githubusercontent.com/81659528/118653133-a7396780-b800-11eb-9386-6a50c7dc0ccd.png)
HELP HERE PLZ!!

**Comment by curseblood123** [comment]
ANYONE ??

**Comment by OscarAkaElvis** [comment]
why posting here? this is not related. Stop spamming or you'll be banned. If you have any issue open a new one or better join to discord to discuss it there.
