### ISSUE TITLE
JtR, beef, hostapd-wpe and asleap are not detected!

### ISSUE THREAD

**Issue by u666sa** [v1s1t0r1sh3r3/airgeddon#359]
I installed all those programs from sources and they work.  I have PATH to their bin directory, etc..  However, airgeddon does not detect them.  What gives and how to fix this?
![Снимок экрана от 2020-03-27 16-22-42](https://user-images.githubusercontent.com/56524166/77760441-66ecb800-7047-11ea-9cf7-61492e253a75.png)

**Comment by OscarAkaElvis** [comment]
Sorry but to help you we need more data... operating system, airgeddon version, etc... all the questions are in the issue creation template (it is shown on your screenshot). It seems you didn't read it. So the issue will be closed. Please, read carefully what is needed to create an issue and read the contributing policy. Otherwise the issue will be closed. Also you can consider to join discord channel looking for help. Closing.

**Comment by u666sa** [comment]
You must be really retarded to need version information for such a simple
question.  Probably you don't speak no English?  Only espanol, you fckign
mexican faggot.
