### ISSUE TITLE
Make the user interface less slow

### ISSUE THREAD

**Issue by KeyofBlueS** [v1s1t0r1sh3r3/airgeddon#361]
#### Describe the feature or compatibility enhancement and involved versions if apply

Hi,

airgeddon ui has extremely poor performance in printing lines on some systems (one line per second on my eeepc 901, maybe the cause is the cpu?), which is frustrating.
I came to the conclusion that the culprit is parsing of language_strings.sh, in fact I tried to edit it leaving english strings only, and now the ui is very very responsive. Even my desktop benefited from this change, it is now surprisingly fast, almost immediate.
In sight of this, is it possible to improve how airgeddon parse language strings? maybe splitting language_strings.sh into different files, one per language (language_strings_english.sh, language_strings_spanish.sh ecc...)?

#### What are the benefits of adding this?

It would make the user interface much faster and more responsive, **needed especially in very slow systems**.

Thanks.

**Comment by OscarAkaElvis** [comment]
Yeah, you are right, if the computer is slow, the performance is poor... I must say i have two computers and it works like a charm on both.

The question about split language strings file into different files was discussed sometimes but... the ROI (Return of Invesment) is not good. I mean, the team decided that the time needed to spend in order to have them all separated to keep working in a similar way doesn't worth the time to do it, because is not only split... a lot of validations must be done in order to keep airgeddon as "robust" as always. We preferred spend the time to improve other parts or to add new features. What I propose to you is:

Create a plugin to set only one language (english for now) performing an override of the _language_strings_ function. Let's see if that could work as a workaround not only for you. Maybe if you do a good plugin we can add it to Plugins hall of fame section.

More info about plugins system at wiki!
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20System
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Development
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Hall%20of%20Fame

Anyway, we'll take it into consideration for the future. Probably someday we'll need to do the split necessarily. Thanks.

**Comment by KeyofBlueS** [comment]
What if, at run time, starting from language_strings.sh, airgeddon could dinamically make a specific language file?

Dirty proof of concept:

```
language=ENGLISH

languages="ENGLISH SPANISH FRENCH CATALAN PORTUGUESE RUSSIAN GREEK ITALIAN POLISH GERMAN TURKISH"

for language_to_delete in $languages; do
	echo $language_to_delete
	if [ "$language_to_delete" = "$language" ]; then
		true
	else
		if [ -z "$languages_to_delete" ]; then
			languages_to_delete=$language_to_delete
		else
			languages_to_delete="$languages_to_delete|$language_to_delete"
		fi
	fi
done

touch $HOME/airgeddon/master/language_strings_"$language".sh
cat $HOME/airgeddon/master/language_strings.sh | grep -Ev "$languages_to_delete" > $HOME/airgeddon/master/language_strings_"$language".sh
```

something like that. Everything would be done automatically, you shouldn't worry about anything at this point, just maintain language_strings.sh as always, right?

**Comment by OscarAkaElvis** [comment]
Thanks for the idea... as I said, whatever you want to do, you can do it in a plugin. We'll face this maybe in the future, but no in the near future, sorry.

**Comment by KeyofBlueS** [comment]
I don't know if I'll be able to create a plugin, I could try it though.

Don't be sorry,  Thank You instead

**Comment by KeyofBlueS** [comment]
Plugin done, You have mail :)

**Comment by OscarAkaElvis** [comment]
Awesome! I'm checking your plugin now. We can keep talking on Discord Channel. Public invitation link is on wiki contact section

**Comment by OscarAkaElvis** [comment]
Finally, @KeyofBlueS did it... very nice plugin already added to our [Plugins Hall of Fame](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Hall%20of%20Fame). This is the direct link to the plugin:

https://github.com/KeyofBlueS/airgeddon-plugins/blob/master/ui_boost.sh

To use it, just copy the .sh file on plugins dir. That's all. Using it, airgeddon is showing menus really faster.

Definitely good job! 😄
