### ISSUE TITLE
using to same pins over and over when attacking

### ISSUE THREAD

**Issue by Online-Troll-Hunter** [v1s1t0r1sh3r3/airgeddon#363]
What is your airgeddon version?

(5.0.3(1)-release)

using Kali 2019.2 on virtual box version 6.1

Which is the chipset of your wireless card?

Using AWUS036NHA - Atheros AR9271

Issue I am having. 

Didn't want to put bug as its probably me.

Hi When I am running Airgeddon and trying all the attacks it seems to be attacking with the same pins. do you know why? or know what I am doing wrong?

Tried Pixie dust, reaver and bully on pin attack and tried brute on reaver?

Thank you for your help.

**Comment by xpz3** [comment]
Airgeddon has another option to attack the wpa/wpa2. Its called evil twin with captive portal attack. After selecting your wifi Card from the menu and enabling monitor mode you can select option 7 and then option 9 to select the evil twin attack with captive portal. 
Since you have only one wireless card, select no when it asks to enable DoS pursuit mode and then when it asks for the handshake file, select no and capture a handshake for the victim AP. Then start the attack. It may or may not succeed everytime.
Try all these on your own AP and you'll know how things work if you are new to this.

**Comment by OscarAkaElvis** [comment]
Regarding pins... it doesn't matter what pin is used for Pixie Dust attack. A generic one is used I think 12345670. On bruteforce attacks, it doesn't start with the next pin if the attack is not possible to be done due other problems... probably signal, not responding AP, PBC (push button connect ) enabled or  other reasons.

**Comment by OscarAkaElvis** [comment]
Closing due lack of info and inactivity.
