### ISSUE TITLE
Auto installation won't install missing dependencies 

### ISSUE THREAD

**Issue by MiChaelinzo** [v1s1t0r1sh3r3/airgeddon#394]
sslstrip .... Error (Possible package name : sslstrip)

Missing dependencies packages are trying to be installed. Please be patient... 

An error occurred while trying to install dependencies. This may be due to multiple causes. Make sure your internet connection is working. Anyway, you have installed all essential tools so you can continue. You'll miss only some features 
Press [Enter] key to continue...

**I'm connected into an internet**

**Comment by cjb900** [comment]
If you are using Kali Linux sslstrip it was removed from the default repository in it. you can download and install it from here https://github.com/moxie0/sslstrip

**Comment by OscarAkaElvis** [comment]
First of all, you need to fill correctly the issue creation template. Otherwise we won't help you anymore... remember to put all the needed info (airgeddon version, operating system, etc). This is important to be able to help you. Don't make us to work more than the necessary asking you this basic stuff.

Yeah, this is caused because Debian retired sslstrip package from their repos as @cjb900 said, and as a consequence, removed also from all the Debian based Linux distros (Kali, Parrot, etc).

For now, you can try to install it manually. To do that, you have some options:

 - Install it manually from the original repo: https://github.com/moxie0/sslstrip
 - Install the deb package from this repo on which we collected all the deb packages: https://github.com/v1s1t0r1sh3r3/airgeddon_deb_packages

And probably there are more options... but these two are the first which come to my mind now.

Anyway, we are planning in the future to retire sslstrip as dependency for airgeddon. Probably we'll replace it by bettercap if finally we can make sslstrip working ok with newer 2.x versions.

Closing.

**Comment by cjb900** [comment]
@MiChaelinzo you can also join our discord for any future issues or question you have. https://discord.gg/sQ9dgt9

**Comment by OscarAkaElvis** [comment]
This won't be a problem for the next release v10.40 on which ssltrip dependency is removed.
