### ISSUE TITLE
WPS And hidden SSID

### ISSUE THREAD

**Issue by lucasTam** [v1s1t0r1sh3r3/airgeddon#403]
#### What is your airgeddon version?

v10.21

#### What is your Linux O.S. and which version?

wifislack64 2.2

#### Which is the chipset of your wireless card?

TL-WN722N

#### Describe the issue and the steps to reproduce it

when one does the scanning of devices with wps enabled, networks with hidden SSIDs do not appear

So, if I wanted to test the security of my wifi in a wps attack with this script, it would not be possible (obviously I would have the SSID name)

thank you very much for your attention and reading

**Comment by OscarAkaElvis** [comment]
Hi. It's because the wash tool is not showing them. I think we can't do anything from the airgeddon side. Anyway, as a workaround, if you have all the data (bssid, ssid, channel) you can launch an attack prior doing any scan. If you have no target selected, airgeddon will ask to you all the data. So finally you can test the security for WPS on your network.

If you have further questions contact us on Discord channel. Link is in contact section at wiki. Thanks.
