### ISSUE TITLE
A graphical X window system has not been detected. If you already have one, check it's working properly. It's essential for airgeddon. The script can't continue

### ISSUE THREAD

**Issue by aslamshahpd** [v1s1t0r1sh3r3/airgeddon#409]
A graphical X window system has not been detected. If you already have one, check it's working properly. It's essential for airgeddon. The script can't continue

**Comment by cjb900** [comment]
information on this can be found in the FAQ [here ](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-start-airgeddon-i-see-this-message-a-graphical-x-window-system-has-not-been-detected-if-you-already-have-one-check-its-working-properly-its-essential-for-airgeddon-the-script-cant-continue)

**Comment by OscarAkaElvis** [comment]
Yes please, read wiki before opening issues.

**Comment by DOKGMC** [comment]
Use this method, Worked for me. https://www.youtube.com/watch?v=aXjXnz_JALI&ab_channel=RoelVandePaar

**Comment by fate182** [comment]
You need to pass enviroment DISPLAY to root for xhost. If you are root, make

'xhost +SI:localuser:root'

or just use -E flag with sudo:

'sudo -E ./airgeddon.sh'

**Comment by cjb900** [comment]
@fate182 why are you posting to an issue that was closed back in December? 🤔

**Comment by OscarAkaElvis** [comment]
Yeah, this issue was opened a lot of time ago.

Now we haver our wiki more prepared for the typical questions like this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-start-airgeddon-i-see-this-message-a-graphical-x-window-system-has-not-been-detected-if-you-already-have-one-check-its-working-properly-its-essential-for-airgeddon-the-script-cant-continue

**Comment by fate182** [comment]
@cjb900 because this link was in top-5 google results, but did not help me.
