### ISSUE TITLE
mdk4 problem

### ISSUE THREAD

**Issue by kissmorning** [v1s1t0r1sh3r3/airgeddon#413]
Hello there
After the evil twin (fake ap) connection is created. When the mdk4 attack is running, if the target ap is in auto channel mode, the channel changes and the mdk4 attack is interrupted. Is there a solution for this?

**Comment by cjb900** [comment]
Yes there is. 
During a standard Evil Twin attack, your wireless physical card is split into two logical interfaces. One to create the fake Access Point and another to perform the DoS in monitor mode. During the attack, if the target AP is configured in channel "Auto" and if the victim resets it due to lack of connectivity resulting from the DoS attack, once rebooted, it may switch to another channel rendering our attack perform DoS over a wrong channel and the victim re-establish the connectivity.

To avoid the situation explained above, airgeddon implemented the DoS Pursuit Mode. To enable this mode for Evil Twin attacks you'll need an additional (a second one) wireless card that supports monitor mode. The first card will be used as normal and the second one will be used to scan in background looking for the target AP changing channel. If the situation described before happens and the target AP switch its channel, it will be detected by airgeddon and the attack will re-launch the DoS over the new channel alerting us about this. In this way, the target AP is "pursued" even on channel hopping making the Evil Twin a much more effective attack.

**Comment by kissmorning** [comment]
I need to have 2 compatible wifi cards, is it true?

**Comment by xpz3** [comment]
> I need to have 2 compatible wifi cards, is it true?

You need two cards. Main card should support virtual interfaces (monitor mode and master mode at the same time) for performing the evil twin attack and another card that supports monitor mode (no need of virtual interface) to be used for Dos pursuit mode. After selecting the deauth method for evil twin, airgeddon will prompt you whether you want to enable Dos pursuit mode or not. Just select yes there and select your secondary interface.

**Comment by kissmorning** [comment]
i am grateful for your help
