### ISSUE TITLE
Missing OLD FEATURE

### ISSUE THREAD

**Issue by Dylan433447** [v1s1t0r1sh3r3/airgeddon#415]
There were like an old feature but it no longer exist now !  

INTERNET METHOD :    USING   USB    (this option is missing) <---           OTHER OPTION dnsspoof

ONLY WORKS IN AIRGEDDON 9.0
![Screenshot from 2021-01-12 09-25-32](https://user-images.githubusercontent.com/34538048/104273368-696db080-54a7-11eb-9507-90baf648504e.png)
![Screenshot from 2021-01-12 09-25-29](https://user-images.githubusercontent.com/34538048/104273373-6a9edd80-54a7-11eb-841e-4334e8246e62.png)
![Screenshot from 2021-01-12 09-25-23](https://user-images.githubusercontent.com/34538048/104273375-6a9edd80-54a7-11eb-922d-f150f8aaa317.png)

**Comment by cjb900** [comment]
Have you tried the latest version of airgeddon because it no longer uses that feature as it has been replaced and in my tests and others the captive portals work with out needing to have an internet connection.

**Comment by Dylan433447** [comment]
the other one was automatically redirecting me to the other networking without looking for it i swear that happened 2019 but no one belives me its possible i've done it many times  and it was redirecting without me doing anything does it have to do anything with the phone model ? if its old then it  connects to others ? or what? i don't get it

**Comment by OscarAkaElvis** [comment]
Yeah, that was removed a lot of versions ago.... because it was pointless to requiere internet access for captive portal evil twin attack... is much easier to have the dependency of dnsspoof to perform the "DNS blackhole" effect to redirect all the clients to the captive portal. The effect is exactly the same. If you read the changelog you can find on release 9.22 this:

`Removed useless internet access DNS resolution method for captive portal Evil Twin, now pure dnsspoof`

Closing.
