### ISSUE TITLE
Unable to use deauth feature

### ISSUE THREAD

**Issue by gvrosun** [v1s1t0r1sh3r3/airgeddon#425]
#### Is your question related to any concrete technology?

Wireless

#### Describe your question as detailed as possible

I tried deauth using this tool using mdk4 and also aireplay but I can't deauth anyone

My wifi adapter: Alfa AWUS036ACH 2.4 & 5 Ghz USB Wireless Adapter
Chipset: Realtek RTL8812AU chipset

Every options working like monitor mode, deacon flooding, fake ap
But deauth alone not working

**Comment by cjb900** [comment]
your issue is that the chipset you have does not support VIF which is the ability for it to deauth and create the fake AP at the same time. You can see [here ](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets)that this chipset is known to be problematic. The only suggestion would be to get a new one that has been tested and known to work.

**Comment by OscarAkaElvis** [comment]
Read this:

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do
