### ISSUE TITLE
Hashcat utils

### ISSUE THREAD

**Issue by awesomedonald** [v1s1t0r1sh3r3/airgeddon#442]
Why cant it see that i have hashcat utils installed?

**Comment by OscarAkaElvis** [comment]
The question is... why can't you see te rules before opening an issue?

In order to help you, we need to know many things.... airgeddon version, your operating system, etc etc... please, fill fully the questions on the issue creation template. Otherwise is not possible to us to help you.

I'll close this due the lack of that information. For further discussion, join to our Discord channel: https://discord.gg/sQ9dgt9

As a last thing, I'll said that airgeddon is not checking your installed packages. It checks for the binaries it needs. In this case, is a binary called `cap2hccapx.bin` and it is usually located at `/usr/lib/hashcat-utils/cap2hccapx.bin`. If you installed hashcat-utils package... usually that binary should exist and airgeddon will detect it. If you have that binary in other location, tell to us where, what is your OS and how did you installed hashcat-utils package.  In airgeddon there is an array called `possible_hccapx_converter_known_locations` and maybe we could add that location to that array.

**Comment by awesomedonald** [comment]
This line said it all 
/usr/lib/hashcat-utils/cap2hccapx.bin
hashcast-utils folder was in my home folder
i moved it

**Comment by OscarAkaElvis** [comment]
Now you know the answer about why airgeddon is not able to detect it... Because you moved it from the expected path.

**Comment by awesomedonald** [comment]
I didnt move it. That is where it default installed to.

**Comment by OscarAkaElvis** [comment]
Ok. The solution is easy. Move (or copy) it to the expected path. Other "dirtier" solution is to modify airgeddon script adding your custom path to the array I told on my last post. But I don't recommend this because the changes will be lost if an update arrives... Unless you make it creating a plugin, but that is another story...

**Comment by awesomedonald** [comment]
I already moved it and it works fine. Thanks again.
