### ISSUE TITLE
wps reaver pixie dust issue

### ISSUE THREAD

**Issue by MarekCZFM** [v1s1t0r1sh3r3/airgeddon#457]
I have a problem with my pixie dust attack not working, can you advise me how to fix it? here is the error: https://imgur.com/0f9osJJ

**Comment by OscarAkaElvis** [comment]
Sorry but to help you, we need more data... the data you didn't provide to us because you preferred to delete all the stuff in the template to create this issue instead of read it to fill it correctly. I'm not going to start asking you about all we need because you should read it already. Closing due to lack of interest reading while opening an issue.
