### ISSUE TITLE
Making it possible to do WEP attacks with hidden SSID with clients

### ISSUE THREAD

**Issue by jedai47** [v1s1t0r1sh3r3/airgeddon#468]
#### Describe the feature or compatibility enhancement and involved versions if apply

Making it possible to do WEP attacks with hidden SSID with clients as with a deauth attack on the client we can reveal the hidden ssid.

#### What are the benefits of adding this?

Not being rejected by the airgeddon program.

**Comment by OscarAkaElvis** [comment]
To reveal the SSID of a hidden network, you need to be scanning while a client connects to it. Then, the SSID will appear. Yeah, it's true that if you perform DoS over connected clients, then they should reconnect and the SSID should be revealed and then you can launch the attack over the WEP network.

The point is if that worth the time to do it, because as I guess you know, WEP networks are much more than deprecated... nowadays there is no WEP networks anywhere. Maybe you just could plug two cards and open two airgeddon instances, one to keep scanning and other to perform DoS from the DoS menu to the WEP AP and the result could be the same.

Thanks for your suggestion but I think for now this is something that we are not going to develop.
