### ISSUE TITLE
No client connect wait 00:07:00 will show

### ISSUE THREAD

**Issue by Casper-88** [v1s1t0r1sh3r3/airgeddon#481]
#### What is your airgeddon version?
<v11.0>

#### What is your Linux O.S. and which version?
<Kali Linux 2022.1>

#### Which is the chipset of your wireless card?
MT7610U
No client connect wait 00:07:00 will show
dnsmasq: config error is REFUSED (EDE: not ready)
But no effect captive portal still triggered fine.
![Dns](https://user-images.githubusercontent.com/43668267/157893391-50850c0e-1408-476d-b888-44753de08689.png)

**Comment by cjb900** [comment]
@Casper-88 opening a new github issue for the same or similar issue is not going to resolve your issue. As @OscarAkaElvis mentioned in your other issue he was not able to replicate your issue. I also tested this on my kali 2022.1 installed on a laptop and not in a VM and even though i got the same error I had no issues connecting to the fake AP and capturing the password. If your issue is that no victims are connecting to your fake AP that is not an issue with airgeddon or dnsmasq. that is just a limitation of an evil twin attack. Airgeddon does not make victims automatically connect to your fake AP. the victims have to manually connect to the fake AP when they realize they were disconnected from the real one.
![Screenshot_2022-03-11_10_21_15](https://user-images.githubusercontent.com/47070308/157903470-e2807022-7b05-4196-9cb2-01221ae595f5.png)

**Comment by OscarAkaElvis** [comment]
Open one more issue to say the sam and I'll be glad of ban you. First and last warning.

**Comment by Casper-88** [comment]
@OscarAkaElvis 
Sorry, don't how to contact you.
See you no reply. Please don't angry.

**Comment by Casper-88** [comment]
@cjb900 
Thank you testing and reply me.

**Comment by OscarAkaElvis** [comment]
Read wiki. Ther you can find contact methods including discord server.
