### ISSUE TITLE
GPU attacks

### ISSUE THREAD

**Issue by jboissat** [v1s1t0r1sh3r3/airgeddon#484]
Hello

I need your help because I can't get the CPU menu with GPU attacks in the "offline WPA/WPA2 decrypt" option

I installed an nvidia graphics card with the NVIDIA CUDA driver

Can you help me
Thank you

**Comment by OscarAkaElvis** [comment]
GPU attacks are only available from `airgeddon>=11.0`. You didn't fill the issue creation template correctly and now we are wasting our time asking you "what is your airgeddon version?". I'll close it because of a issue creation policy violation. You need to read before ask.

For further help, check our discord channel. Read wiki to find the link to join.
