### ISSUE TITLE
I customize the phishing page, and the webserver prompts "numeric argument required:exit:0"

### ISSUE THREAD

**Issue by czg6666666** [v1s1t0r1sh3r3/airgeddon#491]
I customize the phishing page, and the webserver prompts "numeric argument required:exit:0"
When I enter the password on the phishing page, this prompt will appear on the webserver page, why?

![QQ截图20220430140340](https://user-images.githubusercontent.com/100592614/166093792-92a4f293-0e16-447f-9b76-5b1bb543a16a.png)

**Comment by OscarAkaElvis** [comment]
First of all. You didn't fill correctly the issue creation template... so the issue will be closed. We don't know your OS (guessing is Kali based in wallpaper?), your airgeddon version, in this case could be relevant to know also your lighttpd version, etc... It will depend also of your custom portal development that could be generating errors on web server due to your own code. Anyway, is suspicious to see the TLS warnings... ¿? Captive portal works for http and not for https. Regarding this, read this link: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#once-connected-to-the-evil-twin-fake-network-captive-portal-is-not-triggered-what-am-i-doing-wrong

To create a custom portal, here are some notes: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#can-be-the-evil-twin-captive-portal-page-be-customized-how

Obviously if that errors are not showing up with the default custom portal is because clearly are related to your custom portal development. Impossible to us to know what you did without your code.

Join to our Discord server for further discussion. Maybe we could help you there: https://discord.gg/sQ9dgt9
