### ISSUE TITLE
Why do you force a maximum timeout of 100?

### ISSUE THREAD

**Issue by masterofobzene** [v1s1t0r1sh3r3/airgeddon#495]
Why don't you let us set a higher timeout for the scripts? is there a technical reason?  these audits take hours in some cases, I don't get it.

**Comment by OscarAkaElvis** [comment]
Hi. Usually is enough to perform any action. Anyway if you want to increase the time, it can be done easily creating a plugin to modify it.

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20System

**Comment by masterofobzene** [comment]
Still seems a little bit obtuse to hardcode a maximum at 100 seconds if there is no tech reason and then delegate the "fix" to users, I saw the link and it doesn't explain the "easy" steps to make a plugin to make this basic "feature".

But, its your code after all.
Regards.

**Comment by OscarAkaElvis** [comment]
Really aren't you able to change a number in code?

**Comment by xpz3** [comment]
> Still seems a little bit obtuse to hardcode a maximum at 100 seconds if there is no tech reason and then delegate the "fix" to users, I saw the link and it doesn't explain the "easy" steps to make a plugin to make this basic "feature".
> 
> But, its your code after all. Regards.

I don't lnow what your scenario is but if your setup is right, the majority of people out there could capture a handshake within 20 or 30 seconds. If clients are connected to the AP you're targeting and your deauth works, then the clients will get disconnected and try to connect again when we capture the handshake. Its just a matter of seconds. So I believe 100 secs is more than enough. If you're not able to get a handshake within this time, that means either there are no clients connected or your deauth isn't working. So you need to work on that rather than trying to increase the timeout.
