### ISSUE TITLE
Evil Twin does not properly link to available internet connection 

### ISSUE THREAD

**Issue by Spessmen14** [v1s1t0r1sh3r3/airgeddon#498]
#### What is your airgeddon version?

11.01 

#### What is your Linux O.S. and which version?

Kali linux 5.15-kali3-amd63

#### Which is the chipset of your wireless card?

2x Ralink 5572 - USB WiFi (external)

#### Describe the issue and the steps to reproduce it

1. Boot machine with both USB WiFi interfaces plugged in and recognized by OS.
2. Verify that one of the RaLink devices can indeed access a WiFi network with Internet connectivity.
3. Select available WiFi network for ANY type of Evil Twin attack.
4. Connect device (for example, a smart phone) to the Evil Twinned network.
5. Watch the DHCP assign an IP address to the connecting device.
6. Get a warning on the newly connected advice that the network does not have internet access.
7. Be unable to browse internet (and thus not capture any data) from the joining device.

**Comment by OscarAkaElvis** [comment]
Hi, you'll have no problems losing internet access if you get internet through ethernet interface. If you are accessing internet through one of your wireless adapters, then is normal to lose the access due to the Network Manager killing that airgeddon is doing to avoid problems during the Evil Twin attack. But don't worry, we also thought in this kind of situation. For you, there is an interesting option you can use. Check this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

You can see an option called `AIRGEDDON_FORCE_NETWORK_MANAGER_KILLING`. It is set to true by default. Set it to false and then you'll see that you don't lose internet anymore.

Don't hesitate to join to our Discord channel for further support. Invitation link: https://discord.gg/sQ9dgt9

Closing this.
