### ISSUE TITLE
Not able to start the evil-twin attack properly.!

### ISSUE THREAD

**Issue by dell-devil** [v1s1t0r1sh3r3/airgeddon#500]
#### What is your airgeddon version?

 11.01

#### What is your Linux O.S. and which version?

Kali Linux 2022.1 [5.15.0-kali3-amd64]

#### Which is the chipset of your wireless card?

TP-LINK TL-WN722N v2/3 - Realtek RTL8188EUS (Which Supports Monitor , Injection , AP Mode)

TP-LINK Archer T2U Plus - Realtek RTL8811AU (Which Supports Monitor , Injection , AP Mode)

#### Describe the issue and the steps to reproduce it

1. Connect both the wireless card with the VM having kali linux 2022.1 .
2. Starting Monitor mode in both the cards.
3. Then Opening the airgeddon script.
4. Starting The Evil Twin Attack Menu.
5. VIF is not supported in my both cards but I deauth with one of the cards and make Fake AP with other one.
6. But the issue start here when the attack start Only AP and DHCP Xterm Open other tab are not opening. I don't know why this is happening never happened before.

![issue](https://user-images.githubusercontent.com/65786119/178117900-2e744aec-56ff-4319-8c97-9b91dcb7a410.png)

**Comment by cjb900** [comment]
RTL chipsets are notoriously problematic for wifi hacking even support the modes needed they still always run into issues. which is why they are not recommended for wifi hacking. Also it is not recommended to start monitor mode before starting airgeddon that can cause issues with airgeddon running properly. You need to have airgeddon put what ever cards you are using into monitor mode. But personally I would ditch those cards and get a better more supported one from here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets. If you can't get/afford a better card you can try using this [plugin](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20System) to use 2 cards in airgeddon https://github.com/xpz3/airgeddonplugins/blob/main/multint.sh and see if that helps. But again you are using RTL chipsets so there is no guarantee that plugin will help.

**Comment by dell-devil** [comment]
> RTL chipsets are notoriously problematic for wifi hacking even support the modes needed they still always run into issues. which is why they are not recommended for wifi hacking. Also it is not recommended to start monitor mode before starting airgeddon that can cause issues with airgeddon running properly. You need to have airgeddon put what ever cards you are using into monitor mode. But personally I would ditch those cards and get a better more supported one from here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets. If you can't get/afford a better card you can try using this [plugin](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20System) to use 2 cards in airgeddon https://github.com/xpz3/airgeddonplugins/blob/main/multint.sh and see if that helps. But again you are using RTL chipsets so there is no guarantee that plugin will help.

Thank You @cjb900 that plugin really helped me.
![solved](https://user-images.githubusercontent.com/65786119/178152479-7329e17b-ea10-487c-bb68-66ae0c74aa2a.png)
