### ISSUE TITLE
freezes in airgeddon in "Select an interface to work with:"

### ISSUE THREAD

**Issue by dvogureckiy99** [v1s1t0r1sh3r3/airgeddon#501]
#### What is your airgeddon version?
v11.01

#### What is your Linux O.S. and which version?
both Kali Linux 2022, Ubuntu 20.04 

#### Which is the chipset of your wireless card?
MediaTek MT7612U

#### Describe the issue and the steps to reproduce it
freezes in airgeddon in "Select an interface to work with:"
```
***************************** Interface selection ****************************** 
Select an interface to work with: 
--------- 
1.  enp1s0  // Chipset: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411
2.  wlp2s0 // 2.4Ghz, 5Ghz // Chipset: Intel Corporation Dual Band
3.  wlx0013ef6f1003 3
```
Where 3. - this is my chipset.

**Comment by cjb900** [comment]
You can find information on how to fix this weird interface naming here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

**Comment by OscarAkaElvis** [comment]
I see you have MediaTek MT7612U chipset, probably because your card is Alfa AWUS036ACM which is a very good card. You can check the list of the best cards for wifi hacking here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

As you can see there in the "Additional comments" column, that card is awesome but is not recommended to be used in virtual machines. Not sure if is your case but if you are using virtual machines (doesn't matter if vbox or vmware) then you'll have problems. Get another card or use it in native linux.

First step is to set back your interface names to old wlan0, wlan1, etc... you say you already read the stuff of the link: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

Are you sure you are following the steps right? don't forget to execute the `update-grub` and reboot. Read it carefully. It should work.

If you want further support, join to our Discord channel. There is an entire community there to help you. Invitation link is in our wiki. https://discord.gg/sQ9dgt9

**Comment by dvogureckiy99** [comment]
Thanks, I already solve this problem by step by step following this https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming instructions, but I have got another type of error now: https://superuser.com/questions/1731931/how-to-disable-dnsmasq-listening-on-port-53-on-ubuntu-20-04

**Comment by dvogureckiy99** [comment]
I don't have dnsmasq
