### ISSUE TITLE
Evil Twin AP attack with sniffing and bettercap-sslstrip2/BeEF NEED HELP

### ISSUE THREAD

**Issue by Starc86** [v1s1t0r1sh3r3/airgeddon#517]
I have a Problem running Beef in Airgeddon. 
Beef Standalone working correctly. 

When I open Panel and Login on Beef. I get this Error. 

Can anybody help me to find a Solution ?
<img width="786" alt="Bildschirmfoto 2022-10-20 um 16 17 53" src="https://user-images.githubusercontent.com/17482459/196975406-24d71b21-fb11-428a-84cb-6eaa0e075c6a.png">

**Comment by cjb900** [comment]
Since you failed to fill out the issue template properly this is getting closed. You can consider contacting us on [discord](https://discord.gg/sQ9dgt9) for more direct help

**Comment by OscarAkaElvis** [comment]
Yeah, please, try to give to us all the needed data (read the issue creation template). Anyway, I can tell you that in the airgeddon development version v11.10 (is in dev branch on github, not released yet), there are some changes in order to make BeEF work again. Because it seems they changed the behaviour of the config file.

Read the changelog: https://github.com/v1s1t0r1sh3r3/airgeddon/blob/dev/CHANGELOG.md#1110

**Comment by Starc86** [comment]
Thx for fast Help. Can you Show me the Template I didn't find something about it ? Sry for my Fault. I will check on DC.

**Comment by v1s1t0r1sh3r3** [comment]
Is the text appearing in the same field where you type when you open a new issue.

Check our wiki, on contact section to join our discord server for further help.
