### ISSUE TITLE
About Using 8812au / 8812bu

### ISSUE THREAD

**Issue by LLH-l** [v1s1t0r1sh3r3/airgeddon#524]
Airfeddon is not very compatible with 8812au/8812bu,
This question option occurs in the following options
Ataque deauth aireplay / disassoc amok mdk4
Ataque deauth aireplay

The window flashes back a few seconds after opening (the window crashes)
Is this a device compatibility problem or a driver problem
I searched some information, but didn't mention how to solve the 8812au/8812bu problem

**Comment by cjb900** [comment]
This is not an issue with airgeddon but more an issue with the specific chipsets you have. RTL chipsets are notoriously problematic for with hacking and as you can see from this link these chipsets are not recommended or airgeddon https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets. If you have 2 wifi adapters you may be able to get them to work in airgeddon with the multint.sh plugin here https://github.com/xpz3/airgeddonplugins. But being they are RTL chipsets this is not a guarantee and ditching them for better supported ones from the link above would be recommended.

**Comment by LLH-l** [comment]
Hello, cjb900

I don't think it's a chipset or driver problem

If it is a chipset or driver problem
We done many tests
Try to use the same environment to test and capture the handshake package
For the capture handshake packet function
However, try to use the wifite tool, which can capture the handshake packet (both 8812au/8812bu)
Handshake packets are successfully captured in 2/5g frequency bands

It proves that the driver and chipset are OK, indicating that the authentication cancellation packet can be sent normally
Maybe  need to add a type of authentication revoking attack to it

**Comment by OscarAkaElvis** [comment]
RTL chipsets (not all) have a hardware limitation. Most of them are not VIF (Virtual Interface) capable. What is VIF? read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-fake-ap-is-not-working-on-any-evil-twin-attack-why

You can user RTL chipsets in airgeddon to scan, to get a handshake, or to perform a simple DoS inside airgeddon... but not for complex attacks like Evil Twin attacks. As I see, you were already pointed to the plugin to use two cards instead of one with VIF to perform an Evil Twin attack. I have a RTL8812bu chinese dongle and I can use it flawlessly for these simple tasks with airgeddon. But as I said, is not valid for Evil Twin attack due its hardware limitation. There is nothing to do from airgeddon side beyond the validation that airgeddon already included to check if the card is VIF capable to warn to the user about the problem if his/her card is not VIF capable.

For further discussion join to our Discord server. Invitation link is in contact section at wiki.

**Comment by LLH-l** [comment]
Hello, OscarAkaEIvis

Of course, airdeddon is excellent,
I just want to use it to capture handshakes (I don't want to implement twin attacks. This topic has nothing to do with twin attacks). I just want to use it to capture some hidden aps, but it is incompatible with the 8812au/8812bu and cannot be used to capture handshakes

**Comment by OscarAkaElvis** [comment]
I don't think so. I have a RTL8812bu and I can get handshakes and perform basic DoS. It's true that I don't used my card since time ago. Let me some time to install drivers again and test it again and confirm that it is working for me. Give me some days. But I can tell you that last time it was working flawlessly.

**Comment by LLH-l** [comment]
Whether you are 8812bu or 8812au, when you capture the handshake, you will also have problems like I said

**Comment by OscarAkaElvis** [comment]
Will see... anyway, join to our Discord server to talk further: https://discord.gg/sQ9dgt9

**Comment by OscarAkaElvis** [comment]
Ooooooooooook, one more test.... now this repo: https://github.com/RinCat/RTL88x2BU-Linux-Driver

Easy installation, just launching `make` and then `make install` and after reboot, here it is... card appeared. Yeah, don't blame for still using deprecated iwconfig command... my brain is just old fashioned 😄 

![image](https://user-images.githubusercontent.com/5803348/208601081-ac32e152-0084-4345-a734-2679f9e3fc26.png)

And testing airmon-ng same result as before.... command hangs and never ends 😢 

![image](https://user-images.githubusercontent.com/5803348/208601385-bfa240f3-3072-4736-8e24-8df06ee35968.png)

Now let's use it with airgeddon... let's try to get a handshake:

This time deauth worked for some devices... but no handshake at all 😭 , tested many times...

![image](https://user-images.githubusercontent.com/5803348/208602130-d65793e2-45db-4a0f-a8bc-a903ed05e436.png)

For sure we need to keep looking for another driver...

**Comment by OscarAkaElvis** [comment]
Now tested this one: https://github.com/cilynx/rtl88x2bu

Easy to install, `make` and `make install`.

But... 

![image](https://user-images.githubusercontent.com/5803348/208603868-78d65f5e-cdb3-4798-9bcf-55c8ef47149c.png)

No monitor mode supported... so it's completely useless for wifi hacking.

After all of these failed tests... I'm thinking in update my kernel from 5.17 to a new one 6.x ... I don't have much to lose...

Ok then... is enough for now.

**Comment by LLH-l** [comment]
From the point of view of capturing the handshake function alone, the responsibility should not be attributed to the network card chipset

Because of this model of network card chipset and driver, the handshake can be successfully captured using the following tools
airodump-ng wifite hcxdumptool

Blame it on the  chipset
This is a joke to all the community,

**Comment by OscarAkaElvis** [comment]
I can see now you can't appreciate the testing I'm doing. The result of the test is the same using airodump out of airgeddon. And yes, the card and the driver is very important, I can see now you are the joke because you have no idea about what you are talking about. Locking this. It makes no sense to keep trying to help people like you.
