### ISSUE TITLE
Fail deauth attack in evil twin captive portal

### ISSUE THREAD

**Issue by Who0p5** [v1s1t0r1sh3r3/airgeddon#525]
What is your airgeddon version?
11.10

What is your Linux O.S. and which version?
6.0.0 Kali 

Which is the chipset of your wireless card?
RTL8187L

Airgeddon 11.10

Describe the issue and the steps to reproduce it
When i try the evil twin captive portal attack the deauth attack to retrieve the handshake works great but at the moment of deauth I receive an issues as per the attached snip. I read the FAQ re the chipset I have and mentioned in Airgeddon 10.0 updated drivers were added, I still have issues in Airgeddon 11.10 and was hoping for some feedback. 

I seem to be able to do everything bar kick off my devices. 

![12121212](https://user-images.githubusercontent.com/120648648/207856791-91249fc8-d50b-49a7-93cc-d2bfafbf270c.JPG)

**Comment by OscarAkaElvis** [comment]
Hello, RTL chipsets usually are problematic for wifi hacking. Only some of them are working. I guess you already check the list of the working chipsets: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Based on your comment, you have RTL8187L. That is one of the doubtful chipsets because as you can see in the list, it only will work fine using the right drivers.

Did your card pass the VIF check? read this please: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

Please, join to our Discord server for further help. Invitation link is in wiki at contact section. Thanks. Closing this.
