### ISSUE TITLE
Some packages are not available

### ISSUE THREAD

**Issue by GitHubUserPy** [v1s1t0r1sh3r3/airgeddon#527]
#### Describe the feature or compatibility enhancement and involved versions if apply
I am using the newest version of Arch Linux, and Gnome. I was just wondering, if you say that the "airgeddon" tool is compatible with arch, then why if I run all "Possible Package name: " it doesnt always work. This happens with;

Crunch
Beef 
Asleep
Hostapd-Wpe

There is probably just a special command for these, and if so what are they?

#### What are the benefits of adding this?

More compatibility with systems such as Arch and Arch-Based

**Comment by cjb900** [comment]
I don't personally use any Arch based systems but there is information on installing airgeddon on arch at the bottom of this link https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Installation%20&%20Usage.

**Comment by GitHubUserPy** [comment]
Right but this link doesn't talk about how to install these packages

**Comment by OscarAkaElvis** [comment]
airgeddon is compatible with so many Linux distributions. We didn't get involve about how to install packages. We did it only for Kali, Parrot and BlackArch creating the included plugin "missing dependencies plugin" which install automatically all the missing dependencies for these distros. We did only for that distros because they are the only three with all the required packages in their repositories.

If you are using any other Linux distribution, you should investigate about how to get or install the missing packages. As far as I know, for Arch based Linux, you have a pacman command and using it you'll be able to install many of them. For the rest I can suggest to use Arch AUR package (https://aur.archlinux.org/) or get it in any other way. airgeddon is also available there: 

https://aur.archlinux.org/packages/airgeddon-git?all_deps=1#pkgdeps

From that page you can see all the dependencies which are also available in Arch AUR repos, but bear in mind that airgeddon staff is not the responsible of maintaining that packages but anyway is a good start point to check the name of them.

For further help I suggest you to join our Discord server. You can find the invitation link at wiki on Contact section.

Hope it helps.
