### ISSUE TITLE
Dhcpd Permission denied

### ISSUE THREAD

**Issue by zikrisuanda11** [v1s1t0r1sh3r3/airgeddon#529]
#### What is your airgeddon version?

11.10

#### What is your Linux O.S. and which version?

 Ubuntu 22.04

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Docker

#### Which is the chipset of your wireless card?

RTL8822CE

#### Describe the issue and the steps to reproduce it

permission denied when running dhcpd on docker i already running on sudo 

![image](https://user-images.githubusercontent.com/91446630/218704406-a71e34f8-530b-4a3a-b50c-7c1912ce61ad.png)

**Comment by OscarAkaElvis** [comment]
I can see some weird stuff here... first, is that airgeddon v11.04 doesn't exist. We passed from v11.02 to v11.10... apart from that, you have a card which is not recommended for wifi hacking. You can check in our wiki the recommended cards to work with airgeddon: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets . Your card is not on the blacklist but probably it is because usually, all the RTL cards are blacklisted with very few exceptions. As I said, check the list.

I can see you are using Docker. Ok, we'll need to know the exact docker command you are using. Please put the entire command here. I think you are missing some parameters. Check our wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker%20Linux

I can guess that you are using Wayland graphics instead of X window system based on your Ubuntu version (just a wild guess). Please, check the recent changes in wiki to launch docker command.

I can also suggest to you to use the unreleased yet airgeddon v11.11 from our dev branch (it will reach our master branch very soon). It has improvements for Docker and graphics system detection. `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon`

I can suggest you to join to our Discord server to be able to help you better. You can find the invitation link in the contact section in Wiki.

**Comment by zikrisuanda11** [comment]
ok thanks sir for answer
