### ISSUE TITLE
Airgeddon Evil Twin attack not working properly .

### ISSUE THREAD

**Issue by Dark-Side84** [v1s1t0r1sh3r3/airgeddon#544]
#### What is your airgeddon version?

version 11.20

#### Describe the issue and the steps to reproduce it

The tools work really well with wps, handshake , pmkid , and wep attacks but when i use evil twin attack with the captive portal and I have internet access to be able to host the captive portal . When I do put the handshake and choose the language and am ready to fire it up it lunch 2 terminals and it doesn't lunch the rest if I need to type a command in another terminal it won't let me it freezes and then I'm forced to restart my system to use the terminal again plz help me fix this cause Airgeddon is the most useful tool to me and I like it thanks for all the support and help keep going.

![error](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/89361464/c092ca69-46c2-4066-8849-1c4640f46b49)

**Comment by Dark-Side84** [comment]
What is your Linux O.S. and which version?

6.0.0-kali6-amd64

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

running on VMware Workstation

#### Which is the chipset of your wireless card?

Tp-link - Model: TL-WN722N V3

**Comment by cjb900** [comment]
Well there are several things here. One the evil twin captive portal attack does not use any internet connection. So whether you have one or not would not matter. Second an evil twin attack should not freeze up your computer or VM like that. So there is something wrong there. Third the wifi adapter you have will not work in airgeddon on its own and is probably why you are only getting 2 of the 6 windows. You would need to either have 2 of them and use this multint.sh plugin from here https://github.com/xpz3/airgeddonplugins or get a better supported wifi adapter from our list here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by Dark-Side84** [comment]
> Well there are several things here. One the evil twin captive portal attack does not use any internet connection. So whether you have one or not would not matter. Second an evil twin attack should not freeze up your computer or VM like that. So there is something wrong there. Third the wifi adapter you have will not work in airgeddon on its own and is probably why you are only getting 2 of the 6 windows. You would need to either have 2 of them and use this multint.sh plugin from here https://github.com/xpz3/airgeddonplugins or get a better supported wifi adapter from our list here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

nothing is working I have 2 adapters as u said but it is still the same  and i tried to disconnect from the internet but its also the same thing

**Comment by OscarAkaElvis** [comment]
The thing is pretty simple. airgedddon have so many different Evil Twin attacks but they are separated only in two types:
One to get the wifi password, the captive portal attack. That is not requiring internet access.
The rest to get credentials from victimos. That are requiring internet access.

All the attacks are working in the same way. Using only one VIF supporting adapter. What is VIF? read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

Wiki is plenty of useful information. Almost all the answers are there.

Your card is clearly blacklisted. I think you already checked this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

So you never will be able to run correctly the attacks. The rest are workarounds, external plugins and things not supported directly by airgeddon. So if you are using a plugin to launch Evil twin attacks using two cards instead of one VIF card, that's on your own. If you want people to support you, join our Discord channel and maybe there could be somebody able to give you a hand. But this is not the right place. You can find the Discord's invitation link in our Wiki, on contact section.

Good luck. Locking this.

**Comment by xpz3** [comment]
If you have two cards, you must use this plugin https://raw.githubusercontent.com/xpz3/airgeddonplugins/main/multint.sh or else it wont work. Previously if you think airgeddon worked with just one card of 722nv3, it must not have as either ap or deauth only might have worked and you didn't know about it..
