### ISSUE TITLE
[Bug] Wifi Adaptor fails at the Last stage - Evil Twin

### ISSUE THREAD

**Issue by hbednar** [v1s1t0r1sh3r3/airgeddon#547]
#### What is your airgeddon version?

Git clone from master

#### What is your Linux O.S. and which version?

Parrot Security 5.3

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Proxmox vm

#### Which is the chipset of your wireless card?

Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter

#### Describe the issue and the steps to reproduce it

The wireless adapters work up until this point every time, they work when capturing handshakes and sniffing probes.
This is with the evil twin captive portal option.
![int2](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/71215137/5e608f20-8ac2-45dd-8c3c-3526d03705a9)

![int1](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/71215137/36971857-ac4b-4382-85f5-9d17b0f24c53)

**Comment by OscarAkaElvis** [comment]
The card you have should work flawlessly, but for some reason you are getting errors... check this:

-Maybe your card has become buggy and you need to unplug the card and then plug it in again, or maybe you just need to reboot your whole computer. Seems obvious, but sometimes, if your card becomes frozen for some reason, it works.

-Are you using long interface names? if that is the case, you should read and follow these instructions: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

-Try to launch `airmon-ng check kill` command before launching airgeddon

Anyway, it is not a bug. This works for everybody. If you are having issues, for sure you have something odd on your system. I'd recommend to you to use native linux instead of virtual machines for wifi hacking.

If you require more help, don't hesitate to join to our Discord server and there we'll be glad to try to help you further. This is the invitation link: https://discord.gg/sQ9dgt9

Good luck. Closing
