### ISSUE TITLE
Is it possible to direct the custom portal to a web address?

### ISSUE THREAD

**Issue by applusinc** [v1s1t0r1sh3r3/airgeddon#554]
#### Is your question related to any concrete technology?
Kali Linux 2023.02

#### Describe your question as detailed as possible
Can I direct them directly to an internet address with the custom portal opened in front of the victims? for example https://google.com

**Comment by OscarAkaElvis** [comment]
Evil Twin captive portal attack does not require internet access. So it is not validated to have internet access for this attack. Anyway, not sure what are you asking here. This is how it works:

Once victims connect to the fake netwok, every request they do is automatically redirected to the captive portal due to the DNS blackhole and that is the reason why the portal appears and is detected as a captive portal. It doesn't matter where the request is, it maybe google or whatever. Evil twin captive portal attack is the only attack which try to get the victims wifis password.

Based on these explanations, and assuming that during the attack there is no internet access, I think that the question about if you as an attacker can redirect a victim to an internet address is pointless.

If you want to get passwords from the users instead of their wifi password, then you should try a different Evil twin attack. The rest of the attacks require internet access and are focused in try to get passwords from the surfing of the victims through sniffing and Man in The Middle technique.

You opened two GitHub issues in the same day. Please, I encourage you again to join to our Discord server where you'll find a community of people able to help and to answer this and other questions. Please, don't open Github issues to ask uncertain or broad questions. Do that on Discord. Invitation link: https://discord.gg/sQ9dgt9
