### ISSUE TITLE
Request to make the Airgeddon works on WSL too.

### ISSUE THREAD

**Issue by TYehan** [v1s1t0r1sh3r3/airgeddon#559]
#### Describe the feature or compatibility enhancement and involved versions if apply

Airgeddon isn't working on WSL(Windows Subsystem for Linux).
It seems like it doesn't support WSL.

![image](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/85949077/b8c262ca-d361-4a5b-9846-a2794a9a30df)

#### What are the benefits of adding this?

Personally, I am a huge fan of Airgeddon including my colleagues.
It may be easier to use in WSL for Windows users. 
Because WSL is way faster than a Virtual Machine.

Thanks, Brother.

**Comment by OscarAkaElvis** [comment]
Hello, for now WSL or WSL2 is not compatible with airgeddon as you can see here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Known-Incompatibilities

It was discarded at first sight due to the usb devices mapping problem. I mean, by default, usb wifi devices are not detected in the subsystem. Anyway, there is existing software like this (https://github.com/dorssel/usbipd-win) which was created in 2020 to make the mapping into the WSL. Didn't digged into it yet but this could be an opportunity to check if that could work. If I'm able to map one of my usb wifi adapters into WSL and then try airgeddon (removing the WSL detection and restriction) to see if it could work.

I'll take this into consideration to perform some tests. I'll keep this open for now.

**Comment by TYehan** [comment]
Sounds Great. Let's give it try 🔥.

**Comment by OscarAkaElvis** [comment]
![image](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/5803348/20ac96cc-2713-4cc3-97d9-c3db9a64345b)

This looks promising. I was able to map the card to the wsl subsystem but I still can't see it as a network adapter. There are some still missing steps.

**Comment by OscarAkaElvis** [comment]
hmmm... bad news... it seems to make the usb wifi adapters to work on WSL is not only the mapping thing. You need to compile your own kernel as it is referenced here: https://github.com/dorssel/usbipd-win/issues/345

![image](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/5803348/6f8bb58f-cb73-4efb-8508-0ac012758d35)

So this is a complicated thing that probably almost nobody is going to do. For now it'll be discarded. Closing.
