### ISSUE TITLE
could  not read interface wlan0: no such device

### ISSUE THREAD

**Issue by intro30** [v1s1t0r1sh3r3/airgeddon#563]
#### What is your airgeddon version?
v11.10

#### What is your Linux O.S. and which version?

Linux parrot 6.1.0-1parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Parrot 6.1.15-1parrot1 (2023-04-25) x86_64 GNU/Linux

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?
no, dual boot bare metal

#### Which is the chipset of your wireless card?

i used two wireless cards, both recommended and not working
mediatek m7610u
ralink rt5370

#### Describe the issue and the steps to reproduce it

followed steps exactly according as mentioned in airgeddon, captured hand shake, when I start the attack, the wlan0 is not getting access
![Screenshot at 2023-09-20 16-22-47](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/145619945/ba351419-1ef8-4d54-9b9b-c6fe517e049f)
![Screenshot at 2023-09-20 16-22-07](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/145619945/9c878111-13b1-4c79-acea-5c2968273013)

**Comment by cjb900** [comment]
Since you are using Parrot OS your issue may be related to it using the long wifi interface name and not the standard wlan0, wlan1, wlan2 etc... information on how to fix this can be found here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

**Comment by OscarAkaElvis** [comment]
First thing comes to my mind usually is the chipset but in your  case it seems you are using compatible to airgeddon chipsets (https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets).

Second thing is about the consistent network device naming but I see that while I'm writing this, somebody already pointed on a comment to the right url. So that is the first thing I'd do.

Anyway, I recommend to you to read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-fake-ap-is-not-working-on-any-evil-twin-attack-why

Maybe (if you already fixed the interface names stuff and still suffering this) sounds as simple as sometimes, some cards need to be unplugged and re-plugged again. I have one card which after each use (scan, or getting a handshake or whatever) gets buggy and I have to unplug and re-plug it all the time... that's happening for me only with one of my cards (even being a supported and recommended chipset). Maybe the card is not in very good health because it has so many years, who knows.

Maybe is not directly related, but anyway I recommend to you to update airgeddon. You are using an old version v11.10. after that there are v11.20 and the latest v11.21 . For some reason, parrot didn't released them yet. I contacted parrot administrators about a week ago and they told me that the latest v11.21 version will be available soon on the new Parrot 6 release, but for now we must wait.

Anyway, if you don't want to wait to be able to update using apt, you can git clone the repo and use the latest while parrot is updating their repos.

For further discussion, please join to our Discord server. Invitation link is on contact section at Wiki. Thanks.
