### ISSUE TITLE
Some issue while starting Enterprise Wifi Attack

### ISSUE THREAD

**Issue by lkearers** [v1s1t0r1sh3r3/airgeddon#570]
So Im tring to do Enterprise attack on a wifi network. And face this issue. I have successfully captured and cracked hashes from same Network about a few months ago. I would create a custom certificate from Airgeddon (as default ones are flagged as expired by the script) then use that certificate to start the attack. It worked well enough before but now im getting the following error. Even though i have tried to capture the certificate while performing auth with wifi network and failed to use it. Any help will be appreciated. Thanks a lot

> Configuration file: /tmp/ag.hostapd_wpe.conf
> Using interface w1p2s0 with hwaddr 00:00:00:00:00:00 and ssid "Wifi"
> OpenSSL: tls_global_client_cert - Failed to load client certificate error:140AB18E:SSL routines:SSL _CTX_use_certificate:ca md too weak
> OpenSSL: pending error: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
> TLS: Failed to set global parameters
> Failed to set TLS parameters
> Interface initialization failed
> wlp2s0: interface state UNINITIALIZED->DISABLED
> wlp2s0: AP-DISABLED
> Dw1p2s0: Unable to setup interface.
> wlp2s0; interface state DISABLED->DISABLED
> wlp2s0: AP-DISABLED
> w1p2s0: CTRL-EVENT-TERMINATING
> hostapd_free_hapd_data: Interface w1p2s0 wasn't started
> Bh180211; deinit ifname=wlp2s0 disabled_11b_rates=0)

**Comment by OscarAkaElvis** [comment]
I'm going to close this because you didn't filled up correctly the issue creation template where it is supposed that you should put your chipset, your airgeddon version, your OS, etc... now I'm not going to waste time asking that you should put directly.

Anyway, this sounds like you are using old versions... that was fixed time ago here: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/a2812ef19669c914f31ac65efd057e71cf2e9095

And yeah, the default hostapd-wpe certificates expire soon, but you can create them again just uninstallilng hostapd-wpe and installing it again (short and easy way). Of course the kind of uninstallation you must do is the hard... using --purge if you are using Debian based distro... no ida about your OS, so can't give advise. Good luck.

If you want more help join discord to discuss the topic. Closing.

**Comment by lkearers** [comment]
> I'm going to close this because you didn't filled up correctly the issue creation template where it is supposed that you should put your chipset, your airgeddon version, your OS, etc... now I'm not going to waste time asking that you should put directly.
> 
> Anyway, this sounds like you are using old versions... that was fixed time ago here: [a2812ef](https://github.com/v1s1t0r1sh3r3/airgeddon/commit/a2812ef19669c914f31ac65efd057e71cf2e9095)
> 
> And yeah, the default hostapd-wpe certificates expire soon, but you can create them again just uninstallilng hostapd-wpe and installing it again (short and easy way). Of course the kind of uninstallation you must do is the hard... using --purge if you are using Debian based distro... no ida about your OS, so can't give advise. Good luck.
I figured it 



> I'm going to close this because you didn't filled up correctly the issue creation template where it is supposed that you should put your chipset, your airgeddon version, your OS, etc... now I'm not going to waste time asking that you should put directly.
> 
> Anyway, this sounds like you are using old versions... that was fixed time ago here: [a2812ef](https://github.com/v1s1t0r1sh3r3/airgeddon/commit/a2812ef19669c914f31ac65efd057e71cf2e9095)
> 
> And yeah, the default hostapd-wpe certificates expire soon, but you can create them again just uninstallilng hostapd-wpe and installing it again (short and easy way). Of course the kind of uninstallation you must do is the hard... using --purge if you are using Debian based distro... no ida about your OS, so can't give advise. Good luck.
> 
> If you want more help join discord to discuss the topic. Closing.

i have already figured out the issue, the default certifices airgeddon created was not secure enough, so i created them manually, once i succeeded in creating a valid certificate, i twiked the airgeddon code accordingly. Thanks for ur help, btw.

**Comment by OscarAkaElvis** [comment]
Not sure what you mean... I tested it right now on current latest airgedon version 11.21 using default hostapd-wpe certificates and also creating a custom certificates from airgeddon and it was working flawlessly. So probably you were having problems due to obsolete version. No need to tweak anything, just update.
