### ISSUE TITLE
interface issues

### ISSUE THREAD

**Issue by DingusTech** [v1s1t0r1sh3r3/airgeddon#575]
Dear Airgeddon Developers,  I hope this message finds you well. I am seeking your assistance regarding a network interface issue I encountered while using the Airgeddon tool.  Summary of the Problem: While using Airgeddon, I noticed that only the eth0 interface is displayed by default. However, I have other network interfaces available on my system, such as wlan0 and eth1, that I would like to access and utilize within Airgeddon.  Request for Assistance: I kindly request your guidance and support in resolving this issue and enabling the detection and selection of all available network interfaces in Airgeddon. It would greatly improve the flexibility and functionality of the tool for users like myself who possess multiple network interfaces on their systems.  If possible, please provide instructions or insights on how to access and utilize these additional network interfaces within Airgeddon. Any assistance or recommendations you could offer would be greatly appreciated.  Thank you for your time and attention to this matter. I greatly value your expertise and dedication to developing the Airgeddon tool. I look forward to your response and working towards a resolution.  Sincerely, Dingus Tech®
![0C0718D9-ED71-4AFA-A637-B1E3F7BF1485](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/143655789/bd8a08cc-c962-4f04-8633-b679217b9d07)

**Comment by cjb900** [comment]
It appears that you are using some type of VM. VMs cannot use your computer's built-in wifi adapter, which is why only eth0 is showing. If you want to use your computers built in wifi adapter (assuming it is a supported one. Not all are) you will need to run Kali on hardware and not in a VM. If you want to use the VM and or your built-in wifi adapter does not support the modes needed you will need to get a USB wifi adapter from our list here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
