### ISSUE TITLE
Automatically retry after failed handshake packet capture

### ISSUE THREAD

**Issue by Gralent** [v1s1t0r1sh3r3/airgeddon#582]
Describe the feature or compatibility enhancement and involved versions if apply.
My airgeddon version is 11.22, and I hope that when conducting an attack to obtain a handshake packet, if it fails due to timeout, it can automatically retry instead of stopping (like Fluxion)

What are the benefits of adding this?
When grabbing handshake packets fails, there is no need to always manually restart the attack

**Comment by OscarAkaElvis** [comment]
To stop the attack and launching it again manually is completely intentional. Advantages of doing it this way:

 - This way, the disruption of the wifi service is minimal. Remember that airgeddon is intended to be used on professional pentests  and the idea is to impact the less as possible on the normal operations of a wifi network.
 - If it didn't work at the first shot, probably it will fail at the second either. Probably you need more signal strength or maybe the DoS attack you selected is not affecting the AP or the connected clients, so to reconsider the attack to start it again using a better approach is recommendable. Read more about possible DoS problems: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

But Thank you anyway for the suggestion. Closing.
