### ISSUE TITLE
Can't get any handshake

### ISSUE THREAD

**Issue by JoaoMSacramento** [v1s1t0r1sh3r3/airgeddon#584]
#### What is your airgeddon version?
11.22

#### What is your Linux O.S. and which version?
Kali 6.6.9-arm64 2024.1

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?
Virtualized system in UTM.

#### Which is the chipset of your wireless card?
Realtek RTL8811AU

#### Describe the issue and the steps to reproduce it
I bought a TP-Link Archer T2U Nano (Realtek RTL8811AU) to use with Airgeddon since I saw it was compatible.
It supports both 2.4GHz and 5GHz.

When I launch Airgeddon I can select it and set it in monitor mode but Airgeddon only shows 2.4GHz as "Supported bands".
After that I'm choosing "7. Evil Twins attack menu" -> "4. Explore for targets (monitor mode needed)".

I have no problems with the scan and I choose my home Wifi network.

After select it I choose "9.  Evil Twin AP attack with captive portal (monitor mode needed)".
As soon I choose this option I get the message "The interface wlan0 you have already selected is not supporting VIF (Virtual Interface). This attack needs it to virtually unfold itself to create the fake access point while also performing denial of service (DoS)". I write "y" to continue and it starts to scan the network again.

Again, I choose my network and then the option "2.  Deauth airplay attack".
Then "N" for "DoS pursuit mode", "N" for MAC address spoof, "N" for "captured handshake" and "100" for the timeout value.

It starts to look for an handshake but always with no success. I even tried to disconnect/connect my phone to my wifi network multiple times but it doesn't work.

Does anyone knows why this is happening?

Thank you!

**Comment by OscarAkaElvis** [comment]
Hello, I will answer you giving you some links to read from airgeddon wiki.

Regarding the card you bought... not sure where you saw that card is compatible... because it has a Realtek chipset which is not recommended at all as you can see here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Please, get one from the whitelist. Your chipset is in the blacklist!!! so that's the main cause of all of your problems.

Regarding VIF, what is that? read this to understand why is needed: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

If your DoS is not working read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

To do wifi hacking on a virtual machine is not recommended. A native system is the best choice, anyway, it can be done if you have a nice card.

As a summary, we could say that the root cause of all of your problems is your crappy RTL chipset.

For further help, please join our Discord server. You can find the invitation link on contact section at wiki. Closing.
