### ISSUE TITLE
Color Coding AP List Recommendation

### ISSUE THREAD

**Issue by kn0wledge** [v1s1t0r1sh3r3/airgeddon#60]
Hello @v1s1t0r1sh3r3 , 

Sorry I am new to github and don't know where to post a recommendation. Please let me know for future reference. I enjoy testing this kind of programs and I have tested so far: Fluxion, wifiphisher, and Captive portal for wifi pineapple. 

airgeddon is stable, and the verbosity makes it easy to understand what is happening .. and so far, it is the most stable and flexible of the bunch. So I would like to collaborate in giving as much feedback as possible to make it the ultimate tool. 

Have not yet tested the beef module so I will not comment yet. 

for wifi handshake: super easy to use and effective! 
Recommendation:
1- color code the Client discovery section. Meaning, if AP has clients make it red, if not yellow. if it has WPS then let WPS be in Blue . I also recommend putting all text in bold to make it more visible. 
2- If you can get router discovery detail to show that would be great (check wifiphisher code for that)

I will post more feedback the more I go through it. 

Apologies if it is in the wrong section

**Comment by v1s1t0r1sh3r3** [comment]
Thanks for your feedback. Maybe to colorize APs on AP selection is a good idea at least for APs with and without clients.

Regarding the WPS... I think at the moment is not possible without changing all the code. The point is we are not using `--wps` parameter for airodump-ng. On wps section we are using wash instead. The reason is even if you put `--wps` parameter on airodump-ng to know if the AP has WPS activated or not, the `-w` parameter which writes data on the file which is going to be parsed is not saving anything about WPS... so can't be done in this way. I already reported it into aircrack suite forum https://forum.aircrack-ng.org/index.php?topic=522.0 but it seems nobody take care about it.

It can be done changing all our code and instead of parsing saved file using `-w` paramenter, parsing the screen output which seems less accurate... I think at the moment is something we are not going to do.

Regarding the  router discovery, do you mean once connected into a network, perform network scanning? Not sure if is the point of airgeddon, this could be a "large ground"

**Comment by kn0wledge** [comment]
hey thanks for the quick reply. Understood for WPS, not a must have anyways. For the router discovery, i meant the physical router's brand like D-Link, Cisco, ..etc This could help select which wifi phishing page to serve if it was a firmware upgrade or something. Both Fluxion and Wifiphisher to it very well (wifiphisher automatically selects the page to use depending on the router model detected, pretty cool).

**Comment by v1s1t0r1sh3r3** [comment]
For now, we are going to do only the colorizing. Thanks anyway!

**Comment by v1s1t0r1sh3r3** [comment]
Maybe the colors are not going exactly that... probably "normal" networks (without clients) will be as they are now (standard color of the terminal), and networks with clients could be in yellow or something like that. I think is not too much important, the point is to mark them. I don't like so much the idea of using bold... anyway I think they will be very visible, you'll see... :alien:

**Comment by xtonousou** [comment]
> Meaning, if AP has clients make it red, if not yellow.

Maybe we should add "blinking" text for that. Although, it does not work with all terminal emulators.

**Comment by deltaxflux** [comment]
Need help?

**Comment by kn0wledge** [comment]
Sounds great

**Comment by v1s1t0r1sh3r3** [comment]
No for this @deltaxflux , it was an easy task. Thanks anyway. I really appreciate the intention. If you want to collaborate, you are welcome.

Finally I did 2 changes:
 - On wps network selection menu, blocked networks are appearing in red.
 - On standard airodump network selection menues, networks with clients are appearing now in yellow.

I selected yellow because red in airgeddon always means some kind of problem, and to have clients it's not a problem. For colors, each to his own. Yellow is ok for me and is my script. 😋 

This issue will be closed automatically when the change arrive to master on v6.1

**Comment by deltaxflux** [comment]
@v1s1t0r1sh3r3 
Ok, but maybe a tipp for your  script, we should externalise the arrays.

**Comment by v1s1t0r1sh3r3** [comment]
which arrays? do you mean language_strings arrays? maybe... For now is ok, the script has aprox 500kb of size. If we externalize the strings the structure will be much more complicated... with file versionning to match script and language files, etc... maybe one day will need it, I know, I know...

Thanks for the tip.

**Comment by deltaxflux** [comment]
I did it like so:
https://github.com/deltaxflux/fluxion/commit/cb7148d20d973e0890c2c7492a4c175eeaa93186

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, I'm starting to prepare this to externalize at least the language_strings in other file. Wow, I saw your commit on fluxion script, are you chinese speaker? maybe you can be interested to translate airgeddon into chinese!! aren't you? if yes, let me do the changes to put language_strings in other file and then it will be easier to do!

**Comment by deltaxflux** [comment]
@v1s1t0r1sh3r3 
No I'm not. But I have a language [post](https://github.com/deltaxflux/fluxion/issues/223).
