### ISSUE TITLE
I can't see any network when exploring for targets in airgeddon | dire need of assistance!!

### ISSUE THREAD

**Issue by airamin** [v1s1t0r1sh3r3/airgeddon#600]
What is your airgeddon version?
v11.30

What is your Linux O.S. and which version?
Kali Linux 2024.2

wlan0 used: 
![image](https://github.com/user-attachments/assets/d4ae2669-8095-4086-8693-1a1d999d2f9e)

Describe the issue:
I select explore for targets since I am preparing to launch my evil twin attack for a project, yet, nothing is showing up. Even after I waited for some time...
![image](https://github.com/user-attachments/assets/50cf0c31-3fbd-4cd5-aac9-95ae3e54f235)

I tried rebooting and attaching my wireless adapter multiple times and nothing shows up...
what more can I do? I can't find any posts with a similar problem and im having a hard time (；′⌒`)

pls i am so desperate, i consider myself a good artist, i will draw a fully rendered (half-body) character of your choice with anyone who solves this please 🙏

**Comment by OscarAkaElvis** [comment]
Hello. First of all, you are using one adapter using a chipset which is blacklisted. Most of the Realtek chipsets are crap for wifi hacking. Take a look to the list of the recommended cards/chipsets: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Note about your adapter using v2/v3 which is "the bad one", v1 of that same adapter has a better chipset valid for wifi hacking despite it is supporting only one band (2.4ghz).

Second, probably your problem is because you are using a virtual machine. This is a common problem which happens mostly on VirtualBox. Take a look at our Frequently Asked Questions section at wiki. This is answered there: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-scan-for-wireless-networks-no-networks-are-found

In the wiki you can find also all the info you need. Read it carefully.

As a last suggestion, you can join to our Discord server where there is a community of people able to help on any doubt. Feel free to join. The invitation link is available on contact section at wiki.

Closing.

P.S. Now you owe me an alien character 👽 haha!
