### ISSUE TITLE
cannot connect AP

### ISSUE THREAD

**Issue by AuburnXu** [v1s1t0r1sh3r3/airgeddon#621]
client Can find, but  cannot connect to the disguised AP. Procedure The ip address cannot be obtained

**Comment by OscarAkaElvis** [comment]
Hello, I don't understand the issue. Clearly, there’s a language barrier preventing you from expressing yourself clearly. However, you’re barely providing any data. You haven’t filled out the issue creation template indicating your version of airgeddon, your operating system, the chipset of the wireless adapter you're using, etc.

As stated in the issue creation policy, the issue will be closed immediately for not providing enough information. We don't have time here to play a guessing game.

In addition to vague directions, they are quite imprecise, as I don't see what the IP address has to do with anything related to wireless or airgeddon. And when you refer to "disguised AP," maybe you mean "hidden ESSID"? Too many unknowns.

To continue asking questions, join the Discord server. You can find the info in the contact section of the wiki.

Closing.

**Comment by AuburnXu** [comment]
Sorry, it was after I created the hotspot that the user couldn't connect to it and therefore couldn't open the site to enter the password

**Comment by OscarAkaElvis** [comment]
Too broad... still didn't give all the required information like your OS, airgeddon version, the chipset of your wireless adapter... did you test to connect to the fake AP with your own devices? maybe using a mobile phone? is there any error? any screenshot?

I really encourage you to start thinking about how are you asking questions. You need to provide as much datas as possible. Otherwise, it's impossible to help people like you what are only saying stuff like "it doesn't work" or "clients can't connect to network" and that kind of things.

I'll lock this thread because I guess that you'll keep pushing without any kind of useful information. So again, connect to our discord server for further assistance. And please, don't open another issue. Join discord and there you'll find a community of people willing to help, but remember! you need to be much more clear on your questions. The devil's in the detail.
