### ISSUE TITLE
Targeted Client Deauth for Stealth in Evil Twin Attack

### ISSUE THREAD

**Issue by F4CBR** [v1s1t0r1sh3r3/airgeddon#622]
#### Describe the feature or compatibility enhancement and involved versions if apply

The feature enhancement involves adding the ability to perform a targeted deauthentication attack on a specific client during an evil twin attack. This can be achieved by sending deauthentication packets to one client (using a command similar to aireplay-ng --deauth 0 -a [BSSID] -c [Client_mac] interface) instead of deauthenticating all clients. This feature should be implemented as an enhancement to the current evil twin attack functionality in Airgeddon, ensuring compatibility with the latest versions of the tool.

#### What are the benefits of adding this?

By targeting only one specific client, this feature would reduce the likelihood of detection compared to deauthenticating all clients connected to the access point. It allows for a more focused and efficient attack, increasing the chance of success while minimizing noise.

**Comment by OscarAkaElvis** [comment]
Thanks for the suggestion. This was already considered as you can imagine. The benefit of not being detected also has the disadvantage of reducing the likelihood of success. The less clients affected, the less probability to trick somebody. So to try to affect all clients on a network is intentional.

Maybe I'd consider to add an option in DoS menu for this which could be used for something specific. This could also be used during an Evil Twin attack using a secondary card (and closing the DoS window of the attack) if you want to work on that specific scenario trying that surgical approach.

I'll close this but I'll leave it to be reviewed in the future.

**Comment by F4CBR** [comment]
"The benefit of not being detected also has the disadvantage of reducing the likelihood of success. The less clients affected, the less probability to trick somebody. So to try to affect all clients on a network is intentional". I agree that we could add two options: 1) deauth all clients and 2) deauth a specific client. This would make the Airgeddon tool more comprehensive

**Comment by OscarAkaElvis** [comment]
Could be. I'll take it into consideration.
