### ISSUE TITLE
XTERM window size is 1 x 1.

### ISSUE THREAD

**Issue by MrBlaZe404** [v1s1t0r1sh3r3/airgeddon#624]
#### What is your airgeddon version?

Latest version

#### What is your Linux O.S. and which version?

Kali linux latest version

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Live boot

#### Which is the chipset of your wireless card?

TP-Link WN772N V2

#### Describe the issue and the steps to reproduce it

Hello there!
I just updated Kali Linux and whenever I try to get a handshake or anything that requires an xterm window, the window's size is 1 x 1. Any help?

**Comment by cjb900** [comment]
Your Xterm issue is a known one as mentioned here https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612. But you also have a completely crap wifi adapter/chipset. As you can see it's on our blacklist here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets#blacklist. So even after fixing the Xterm issue, you are not going to properly be able to use airgeddon with that crap wifi adapter and will need to ditch it and get a better one.

**Comment by MrBlaZe404** [comment]
> Your Xterm issue is a known one as mentioned here #612. But you also have a completely crap wifi adapter/chipset. As you can see it's on our blacklist here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets#blacklist. So even after fixing the Xterm issue, you are not going to properly be able to use airgeddon with that crap wifi adapter and will need to ditch it and get a better one.

First of all, thank you so much for the fix, it worked! Furthermore, you can actually install custom drivers for the network card to make it support monitor mode, and it actually works great 😃

**Comment by OscarAkaElvis** [comment]
even if it supports monitor mode, that adapter is not VIF capable. It's a hardware limitation and there is nothing you can do to make it work in that way. Read about what is VIF here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

Get a good wifi adapter from the whitelist using the link of our wiki that cjb900 posted above. Otherwise, you'll obtain unintended behaviours while using airgeddon. Your card is not recommended.
