### ISSUE TITLE
Alfa AWUS036AXML on Kali VM. Not finding? What do i wrong

### ISSUE THREAD

**Issue by Warhammar** [v1s1t0r1sh3r3/airgeddon#635]
Hi folk, 

I made extra a new fresh installation of kali to get the drivers from Alfa AWUS036AXML. Those are there but my pc does find them. 
- lsusb not finding any device. 

What is the exact way to install exactly this Alfa AWUS036AXML device with the chip.

**Comment by OscarAkaElvis** [comment]
This issue is not related directly to airgeddon. Please, join the Discord server and ask in #offtopic for support.

Anyway, I'd say that it should be automatically detected as long as Kali has drivers directly integrated. So it should work out of the box. Another different story would be to be trying to use a virtual machine, where first you should install correctly the drivers on your host O.S. and then map it correctly to the vm selecting usb 3.x as the speed of the usb. Closing.
