### ISSUE TITLE
You have bully installed (v1.0-22), but not required version. To perform Pixie Dust integrated bully attack you must have at least version v1.1 "

### ISSUE THREAD

**Issue by Chintu91** [v1s1t0r1sh3r3/airgeddon#64]
#### What is your airgeddon version?
airgeddon script v6.1 

#### What is your Linux O.S. and which version?
kali sana 2.0

#### Which is the chipset of your wireless card?
Ralink Technology, Corp. RT2501/RT2573

*Insert answer here if apply*

#### Describe the issue and the steps to reproduce it
 
When i go  WPS attacks menu then i select  7.  (bully) Pixie Dust attack  its give me error 
"You have bully installed (v1.0-22), but not required version. To perform Pixie Dust integrated bully attack you must have at least version v1.1 "
i try to manual updated but not work

root@kali:~# apt-get install bully
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bully is already the newest version (1.0-22-0kali2).
bully set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1978 not upgraded.

how update my bully pleaSE GUIDE ME
Thank you advance

**Comment by OscarAkaElvis** [comment]
Install last version (is not in Kali repositories). Follow the instructions in bully project on Github: https://github.com/aanarchyy/bully

If compiling you get a compile error, try downgrading libssl-dev lib: `apt-get remove libssl-dev`and then install old version `apt-get install libssl1.0-dev`. It will compile without any errors. Then, you can overwrite your /usr/bin/bully with /usr/local/bin/bully version in order to use compiled version from anywhere on the system. You can check your version with `bully -V`.

I'm closing this issue, is not an issue of airgeddon.

**Comment by Chintu91** [comment]
Thx men

its working
