### ISSUE TITLE
exploring targets error

### ISSUE THREAD

**Issue by wice22** [v1s1t0r1sh3r3/airgeddon#73]
- Please, answer the questions to provide maximum of info.
 - Answer ALWAYS in english.
 - If more info is needed and requested by airgeddon staff but there is no answer in 10 days, the issue will be closed.

#### What is your airgeddon version? 

*Welcome to airgeddon script v6.12*

#### What is your Linux O.S. and which version?
*Kali latest*

#### Which is the chipset of your wireless card?
*alfa black*

#### Describe the issue and the steps to reproduce it

***************************** Exploring for targets *****************************
Exploring for targets option chosen (monitor mode needed)

Selected interface wlan0mon is in monitor mode. Exploration can be performed

When started, press [Ctrl+C] to stop...
Press [Enter] key to continue...
./airgeddon.sh: line 6116: /tmp/nws-01.csv: No such file or directory

No networks found
Press [Enter] key to continue...*
* ls -la /
drwxrwxrwt  12 root root  4096 Apr 10 16:22 tmp*

**Comment by v1s1t0r1sh3r3** [comment]
I guess it starting to work. Sometimes is better to rebbot, re-plug usb wireless interfaces, try again before posting issue. 😄

**Comment by snowhurt** [comment]
Hey. A relative noob here. I've come across the most vague problem (to me, at least). I'm halfway through setting up airgeddon, I've made sure Monitor Mode is engaged, I'm in the WPS menu, and I've selected 4. Explore for targets. 
***************************** Exploring for targets *****************************
Exploring for targets option chosen (monitor mode needed)

Selected interface wlan0mon is in monitor mode. Exploration can be performed

It seems this interface was parametrized before. It's not necessary to check again

WPS filter enabled in scan. When started, press [Ctrl+C] to stop...
Press [Enter] key to continue...

An unexpected error occurrred, redirecting to menu
Press [Enter] key to continue...

Here's a screenshot as well, if that helps. Can someone explain what happened?  
 
![unexpected](https://user-images.githubusercontent.com/42878395/45067806-48e8ec80-b08a-11e8-8a04-27101b847a0f.png)

**Comment by OscarAkaElvis** [comment]
Sorry but we can't help you in this way. You are not providing any data. You are just saying "hey, i have an error".

Open a new issue and provide all the needed info filling the issue template: airgeddon version, OS and version, chipset of your card, is your card airmon compatible? I deduced from your screenshot that yes, because the card name is wlan0mon so it was changed setting it in monitor mode... Put the steps to reproduce it... just only happening on wps scanning or is happening also on a standard airodump scanning like on the DoS menu for example? that kind of things... locking this.
