### ISSUE TITLE
how to run in docker with wifi card? 

### ISSUE THREAD

**Issue by 0000x0** [v1s1t0r1sh3r3/airgeddon#83]
well they working perfect in docker :) just one problem cant find a way geting work an of my 3 wifi cards on laptop ... any suggessions :)

thats probably mental isusse :) 

im new in docker

**Comment by v1s1t0r1sh3r3** [comment]
Not sure to understand. Is working for you with one of your cards but is not working for other? In that case is a driver issue.

This is too broad. Start providing to us data: Host O.S. , airgeddon version, wireless chipset of your card.

Did you followed the Docker instructions on Wiki? https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker

**Comment by 0000x0** [comment]
docker run -t -i v1s1t0r1sh3r3/airgeddon /bin/bash


***************************** Interface selection ****************************** 
Select an interface to work with : 
--------- 
1.  eth0@if10 // Chipset: Unknown 
--------- 
*Hint* Every time you see a text with the prefix [PoT] acronym for "Pending of Translation", means the translation has been automatically generated and is still pending of review 
--------- 

:)

**Comment by v1s1t0r1sh3r3** [comment]
What the hell? did you read something about how to run it on docker container? Everything is on wiki.

You don't have to run bash at the end of docker run command because the image has already an entrypoint to execute automatically airgeddon... you are not using --net=host so you can't access to the network cards... and many more...

please BEFORE OPENING AN ISSUE READ CAREFULLY THE WIKI.

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker%20Linux

**Comment by 0000x0** [comment]
v1s1t0r1sh3r3 thanx that wot i was lucking for brother 👍

**Comment by OnArs** [comment]
@v1s1t0r1sh3r3 why there is no wifi interface in the list?
![image](https://cloud.githubusercontent.com/assets/6703684/25843642/a9678a78-34b0-11e7-9cea-1d88a4090d80.png)

As a topic starter I use docker via XQuartz

**Comment by OscarAkaElvis** [comment]
If you read the docker for Mac wiki secition [here](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker%20Mac%20OSX) you'll see that is under investigation phase. To be exact, this is the text exposed on that section:

>This is under development. The part of connecting to X Window system is working. Investigating yet how to connect wireless interfaces into docker container.

So is not working yet for Mac and Windows. For now, you must install a Linux vm and then you can install docker on it and run airgeddon container.

The main problem is under Mac/Windows there is no native support for docker. It works depending of the version "tricking"... for example, if you install Docker tool-box, it creates a virtualbox linux machine which acts as a host for the containers. The problem is that vm has nor kernel features neither drivers to work with wireless interfaces.

v1s1t0r/me are investigating how to create a custom boot2docker iso file with wireless support compiling a custom kernel and adding as much as possible wireless drivers but is not working yet. No documentation, no help... is the hard way... we searched through web, irc, google, stackoverflow, etc... and nobody seems to documented how to use wireless devices on docker containers for Win/Mac. So maybe one day could be possible... who knows. Wish us luck! :smile:

**Comment by OscarAkaElvis** [comment]
If you are interested on this (the last part of the conversation, not the issue title because it wasn't an issue), I mean about how to connect wireless interfaces on a docker container under Win/OSX. You can check the progress here: https://github.com/boot2docker/boot2docker/issues/1253

And here: http://stackoverflow.com/questions/43328155/customize-boot2docker-iso-to-use-wireless-devices-on-containers-docker-toolbox
