### ISSUE TITLE
Add a new option

### ISSUE THREAD

**Issue by insanitus** [v1s1t0r1sh3r3/airgeddon#90]
#### What is your airgeddon version?

airgeddon script v6.1

#### What is your Linux O.S. and which version?

Gentoo

#### Which is the chipset of your wireless card?

 Alfa

#### Describe the issue and the steps to reproduce it

 Instead of do a new scan for new targets, try to add the option of choose a new target from the previous scan  

 Thanks for your time, have a nice day (n__n)

**Comment by v1s1t0r1sh3r3** [comment]
Hi, thanks for your comments. The way in which is done is absolutely intentional. The reason is sometimes, the APs are configured on channel "Auto". There are more and more Access Points configured in that way.

With that configuration, the channel of an AP may change. If you save the results of an initial scan and then you start to perform different attacks or actions, the channel of the AP could be changed while you proceed if you take some time doing your action, so the way to avoid that problem is forcing to scan each time before an attack. It doesn't take so much time and save a lot of errors, believe me! 😋 

Anyway, thanks for your suggestion.
