### ISSUE TITLE
No Internet Access When Giving Internet Access from an Android Hotspot

### ISSUE THREAD

**Issue by JavaRockstar** [v1s1t0r1sh3r3/airgeddon#92]
Hi I have installed Kali Linux 2017.1 and Airgeddon I'm using an external Alfa as my monitor card & a TPLink External USB for my managed interface.

I'm using internal Intel Wifi as my Internet connection. I'm connecting to a Portable Mobile Hotspot on a Android Phone.

I have a laptop to do some testing with it has Windows 10 I connect to access point however it still does not get Internet but it does successfully assign an IP to it when using my mobile my Internet hosts local IP becomes 192.168.43.49 and I was wondering due to this IP range could this be the problem why it does not get Internet access by the way really nice script great work.

Also have you used a Mobile Hotspot before with airgeddon or a 3g modem thanks in advance.

**Comment by xtonousou** [comment]
`airgeddon` handles the local IP, this is not the problem. I connected my machine to an Android hotspot and tried to reproduce the issue but all seem to be just fine.

![](https://transfer.sh/MerHt/2017-05-15_012335_522128291.png)

Could you provide us more info, and screenshots if possible?

**Comment by v1s1t0r1sh3r3** [comment]
I think the problem is not related to any android hotspot or whatever... the problem is you can't provide internet with one wireless interface while using other to create the Evil Twin. The reason is hostapd (needed for fake AP creation) needs to perform a "airmon-ng check kill" command to work. So doing that, it kills NetworkManager processes and your managed interface what is serving internet connection stops working because it seems you are using NetworkManager to connect to wireless.

This was discussed before [here](https://github.com/v1s1t0r1sh3r3/airgeddon/issues/76). It seems it has no solution. If you don't kill that processes you can't create AP. If you kill the processes you can't get internet access because killed NetworkManager is what provides internet on a wireless interface. So you have these options:

 - You can get internet from ethernet interfaces.

 - You can install a virtual machine using virtualbox or vmware on which your host's wireless card is going to be detected as eth0 on the virtual machine (this always happens). In this way you can have internet through wireless because for the Linux system is an ethernet card (usually eth0) and you can use another wifi card for hostapd.
 - You can use a system on which there is no network-manager and connect to internet with one of your wifi card using a different method (wpa_supplicant for example).
